import { type RawWordFamily } from './schema';

/**
 * Society, law, government, culture and media — the opinion topics, where the
 * examiner is listening for a position held consistently across four sentences
 * rather than for rare words.
 *
 * These families carry the most `-tion` nouns in the corpus, which is not an
 * accident of topic: abstract argument is built out of them, and `-tion` is the
 * ending a Bengali speaker most often writes as `-sion`. The rule family on
 * each of those entries is `tion_sion` so the screen names the trap.
 */
export const FAMILIES_SOCIETY: readonly RawWordFamily[] = [
  { root: 'society', bangla: 'সমাজ', rule: 'y_to_i', skills: 'SWLR', topic: 'society',
    forms: 'societies:n social:adj socially:adv socialise:v antisocial:adj sociable:adj' },
  { root: 'community', bangla: 'সম্প্রদায়', rule: 'y_to_i', skills: 'SWLR', topic: 'society',
    forms: 'communities:n communal:adj communally:adv' },
  { root: 'popular', bangla: 'জনপ্রিয়', rule: null, skills: 'SWLR', topic: 'society',
    forms: 'popularly:adv popularity:n popularise:v unpopular:adj' },
  { root: 'populate', bangla: 'বসতি স্থাপন করা', rule: 'drop_silent_e', skills: 'WLR', topic: 'society',
    forms: 'populated:adj populating:v population:n populations:n overpopulation:n depopulate:v' },
  { root: 'citizen', bangla: 'নাগরিক', rule: null, skills: 'SWLR', topic: 'society',
    forms: 'citizens:n citizenship:n civic:adj civil:adj civilian:n' },
  { root: 'equal', bangla: 'সমান', rule: null, skills: 'SWLR', topic: 'society',
    forms: 'equally:adv equality:n equalise:v unequal:adj inequality:n' },
  { root: 'diverse', bangla: 'বৈচিত্র্যময়', rule: 'drop_silent_e', skills: 'SWR', topic: 'society',
    forms: 'diversely:adv diversity:n diversify:v diversification:n' },
  { root: 'discriminate', bangla: 'বৈষম্য করা', rule: 'drop_silent_e', skills: 'WR', topic: 'society',
    forms: 'discriminated:v discriminating:adj discrimination:n discriminatory:adj' },
  { root: 'integrate', bangla: 'একীভূত করা', rule: 'drop_silent_e', skills: 'WR', topic: 'society',
    forms: 'integrated:adj integrating:v integration:n disintegrate:v' },
  { root: 'migrate', bangla: 'অভিবাসন করা', rule: 'drop_silent_e', skills: 'WLR', topic: 'society',
    forms: 'migrated:v migrating:adj migration:n migrant:n immigrant:n immigration:n emigrate:v' },
  { root: 'deprive', bangla: 'বঞ্চিত করা', rule: 'drop_silent_e', skills: 'WR', topic: 'society',
    forms: 'deprived:adj depriving:v deprivation:n underprivileged:adj' },
  { root: 'homeless', bangla: 'গৃহহীন', rule: null, skills: 'SWLR', topic: 'society',
    forms: 'homelessness:n home:n homely:adj homeland:n' },
  { root: 'charity', bangla: 'দাতব্য', rule: 'y_to_i', skills: 'SWLR', topic: 'society',
    forms: 'charities:n charitable:adj charitably:adv uncharitable:adj' },
  { root: 'welfare', bangla: 'কল্যাণ', rule: null, skills: 'WR', topic: 'society',
    forms: 'wellbeing:n welfarist:n' },
  { root: 'support', bangla: 'সমর্থন করা', rule: null, skills: 'SWLR', topic: 'society',
    forms: 'supported:adj supporting:adj supporter:n supportive:adj unsupported:adj' },
  { root: 'depend', bangla: 'নির্ভর করা', rule: null, skills: 'SWLR', topic: 'society',
    forms: 'depended:v depending:v dependent:adj dependence:n dependable:adj independent:adj independence:n independently:adv' },
  { root: 'tradition', bangla: 'ঐতিহ্য', rule: 'tion_sion', skills: 'SWLR', topic: 'culture',
    forms: 'traditions:n traditional:adj traditionally:adv untraditional:adj' },
  { root: 'culture', bangla: 'সংস্কৃতি', rule: 'drop_silent_e', skills: 'SWLR', topic: 'culture',
    forms: 'cultured:adj cultures:n cultural:adj culturally:adv multicultural:adj' },
  { root: 'ritual', bangla: 'আচার-অনুষ্ঠান', rule: null, skills: 'SLR', topic: 'culture',
    forms: 'rituals:n ritualistic:adj ritually:adv' },
  { root: 'heritage', bangla: 'উত্তরাধিকার', rule: null, skills: 'WLR', topic: 'culture',
    forms: 'inherit:v inherited:adj inheritance:n' },
  { root: 'history', bangla: 'ইতিহাস', rule: 'y_to_i', skills: 'SWLR', topic: 'culture',
    forms: 'histories:n historic:adj historical:adj historically:adv historian:n prehistoric:adj' },
  { root: 'ancient', bangla: 'প্রাচীন', rule: null, skills: 'WLR', topic: 'culture',
    forms: 'anciently:adv antiquity:n antique:n' },
  { root: 'modern', bangla: 'আধুনিক', rule: null, skills: 'SWLR', topic: 'culture',
    forms: 'modernise:v modernisation:n modernity:n postmodern:adj' },
  { root: 'art', bangla: 'শিল্প', rule: null, skills: 'SWLR', topic: 'culture',
    forms: 'arts:n artist:n artistic:adj artistically:adv artwork:n' },
  { root: 'music', bangla: 'সংগীত', rule: null, skills: 'SWLR', topic: 'culture',
    forms: 'musical:adj musically:adv musician:n unmusical:adj' },
  { root: 'theatre', bangla: 'নাট্যশালা', rule: null, skills: 'SLR', topic: 'culture',
    forms: 'theatres:n theatrical:adj theatrically:adv' },
  { root: 'religion', bangla: 'ধর্ম', rule: null, skills: 'SWLR', topic: 'culture',
    forms: 'religions:n religious:adj religiously:adv irreligious:adj' },
  { root: 'celebrate', bangla: 'উদযাপন করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'culture',
    forms: 'celebrated:adj celebrating:v celebration:n celebrations:n celebrity:n' },
  { root: 'festival', bangla: 'উৎসব', rule: null, skills: 'SWLR', topic: 'culture',
    forms: 'festivals:n festive:adj festivity:n' },
  { root: 'identity', bangla: 'পরিচয়', rule: 'y_to_i', skills: 'SWR', topic: 'society',
    forms: 'identities:n identify:v identified:adj identifiable:adj unidentified:adj identical:adj' },

  { root: 'govern', bangla: 'শাসন করা', rule: null, skills: 'SWLR', topic: 'government',
    forms: 'governed:v governing:adj government:n governments:n governor:n governance:n ungoverned:adj' },
  { root: 'politics', bangla: 'রাজনীতি', rule: null, skills: 'SWLR', topic: 'government',
    forms: 'political:adj politically:adv politician:n apolitical:adj' },
  { root: 'democracy', bangla: 'গণতন্ত্র', rule: 'y_to_i', skills: 'SWLR', topic: 'government',
    forms: 'democracies:n democratic:adj democratically:adv undemocratic:adj' },
  { root: 'elect', bangla: 'নির্বাচন করা', rule: 'tion_sion', skills: 'SWLR', topic: 'government',
    forms: 'elected:adj electing:v election:n elections:n electoral:adj electorate:n reelect:v' },
  { root: 'vote', bangla: 'ভোট দেওয়া', rule: 'drop_silent_e', skills: 'SWLR', topic: 'government',
    forms: 'voted:v voting:n voter:n voters:n votes:n' },
  { root: 'policy', bangla: 'নীতি', rule: 'y_to_i', skills: 'SWLR', topic: 'government',
    forms: 'policies:n policymaker:n' },
  { root: 'authority', bangla: 'কর্তৃপক্ষ', rule: 'y_to_i', skills: 'WLR', topic: 'government',
    forms: 'authorities:n authoritative:adj authoritarian:adj authorise:v unauthorised:adj' },
  { root: 'regulate', bangla: 'নিয়ন্ত্রণ করা', rule: 'drop_silent_e', skills: 'WR', topic: 'government',
    forms: 'regulated:adj regulating:v regulation:n regulations:n regulator:n deregulate:v unregulated:adj' },
  { root: 'reform', bangla: 'সংস্কার করা', rule: null, skills: 'WR', topic: 'government',
    forms: 'reformed:adj reforming:v reforms:n reformer:n' },
  { root: 'nation', bangla: 'জাতি', rule: 'tion_sion', skills: 'SWLR', topic: 'government',
    forms: 'nations:n national:adj nationally:adv nationality:n nationwide:adj international:adj internationally:adv' },
  { root: 'globe', bangla: 'বিশ্ব', rule: 'drop_silent_e', skills: 'SWLR', topic: 'government',
    forms: 'global:adj globally:adv globalise:v globalisation:n' },
  { root: 'law', bangla: 'আইন', rule: null, skills: 'SWLR', topic: 'law',
    forms: 'laws:n lawful:adj lawfully:adv unlawful:adj lawyer:n lawsuit:n' },
  { root: 'legal', bangla: 'আইনসম্মত', rule: null, skills: 'SWLR', topic: 'law',
    forms: 'legally:adv legality:n illegal:adj illegally:adv legalise:v' },
  { root: 'crime', bangla: 'অপরাধ', rule: null, skills: 'SWLR', topic: 'law',
    forms: 'crimes:n criminal:adj criminally:adv criminality:n incriminate:v' },
  { root: 'punish', bangla: 'শাস্তি দেওয়া', rule: null, skills: 'SWLR', topic: 'law',
    forms: 'punished:v punishing:adj punishment:n punishments:n punitive:adj unpunished:adj' },
  { root: 'justice', bangla: 'ন্যায়বিচার', rule: null, skills: 'SWR', topic: 'law',
    forms: 'just:adj justly:adv injustice:n justify:v justified:adj justification:n unjustified:adj' },
  { root: 'court', bangla: 'আদালত', rule: null, skills: 'LR', topic: 'law',
    forms: 'courts:n courtroom:n courthouse:n' },
  { root: 'judge', bangla: 'বিচার করা', rule: 'dge_after_short_vowel', skills: 'SWLR', topic: 'law',
    forms: 'judged:v judging:v judgement:n judges:n misjudge:v prejudge:v' },
  { root: 'accuse', bangla: 'অভিযোগ করা', rule: 'drop_silent_e', skills: 'LR', topic: 'law',
    forms: 'accused:adj accusing:adj accusation:n accusations:n' },
  { root: 'guilty', bangla: 'দোষী', rule: 'y_to_i', skills: 'SLR', topic: 'law',
    forms: 'guilt:n guiltily:adv guiltier:adj guiltless:adj' },
  { root: 'enforce', bangla: 'কার্যকর করা', rule: 'drop_silent_e', skills: 'WR', topic: 'law',
    forms: 'enforced:adj enforcing:v enforcement:n enforceable:adj unenforceable:adj' },
  { root: 'permit', bangla: 'অনুমতি দেওয়া', rule: 'doubling_1_1_1', skills: 'SWLR', topic: 'law',
    forms: 'permitted:adj permitting:v permission:n permits:n permissible:adj impermissible:adj' },
  { root: 'forbid', bangla: 'নিষেধ করা', rule: 'doubling_1_1_1', skills: 'LR', topic: 'law',
    forms: 'forbade:v forbidden:adj forbidding:adj' },
  { root: 'right', bangla: 'অধিকার', rule: 'silent_letters', skills: 'SWLR', topic: 'law',
    forms: 'rights:n rightly:adv rightful:adj rightfully:adv' },
  { root: 'free', bangla: 'মুক্ত', rule: null, skills: 'SWLR', topic: 'law',
    forms: 'freed:v freeing:v freedom:n freely:adv freer:adj' },
  { root: 'privacy', bangla: 'গোপনীয়তা', rule: null, skills: 'SWLR', topic: 'law',
    forms: 'private:adj privately:adv privatise:v' },
  { root: 'secure', bangla: 'নিরাপদ করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'law',
    forms: 'secured:adj securing:v securely:adv security:n insecure:adj insecurity:n' },
  { root: 'safe', bangla: 'নিরাপদ', rule: null, skills: 'SWLR', topic: 'law',
    forms: 'safely:adv safer:adj safest:adj safety:n unsafe:adj' },
  { root: 'corrupt', bangla: 'দুর্নীতিগ্রস্ত', rule: 'tion_sion', skills: 'WR', topic: 'government',
    forms: 'corrupted:adj corrupting:adj corruption:n incorruptible:adj' },
  { root: 'protest', bangla: 'প্রতিবাদ করা', rule: null, skills: 'LR', topic: 'government',
    forms: 'protested:v protesting:v protests:n protester:n' },

  { root: 'media', bangla: 'গণমাধ্যম', rule: null, skills: 'SWLR', topic: 'media',
    forms: 'medium:n mediate:v mediation:n' },
  { root: 'advertise', bangla: 'বিজ্ঞাপন দেওয়া', rule: 'drop_silent_e', skills: 'SWLR', topic: 'media',
    forms: 'advertised:adj advertising:n advertisement:n advertisements:n advertiser:n' },
  { root: 'broadcast', bangla: 'সম্প্রচার করা', rule: null, skills: 'LR', topic: 'media',
    forms: 'broadcasting:n broadcaster:n broadcasts:n' },
  { root: 'journal', bangla: 'সাময়িকী', rule: null, skills: 'WR', topic: 'media',
    forms: 'journals:n journalist:n journalism:n journalistic:adj' },
  { root: 'publish', bangla: 'প্রকাশ করা', rule: null, skills: 'WR', topic: 'media',
    forms: 'published:adj publishing:n publisher:n unpublished:adj' },
  { root: 'public', bangla: 'জনসাধারণ', rule: null, skills: 'SWLR', topic: 'media',
    forms: 'publicly:adv publicity:n publicise:v' },
  { root: 'inform', bangla: 'জানানো', rule: 'tion_sion', skills: 'SWLR', topic: 'media',
    forms: 'informed:adj informing:v information:n informative:adj informant:n uninformed:adj misinform:v' },
  { root: 'report', bangla: 'প্রতিবেদন করা', rule: null, skills: 'SWLR', topic: 'media',
    forms: 'reported:adj reporting:n reporter:n reports:n unreported:adj' },
  { root: 'influence', bangla: 'প্রভাব', rule: 'drop_silent_e', skills: 'SWLR', topic: 'media',
    forms: 'influenced:adj influencing:v influential:adj influentially:adv uninfluenced:adj' },
  { root: 'persuade', bangla: 'রাজি করানো', rule: 'drop_silent_e', skills: 'SWR', topic: 'argument',
    forms: 'persuaded:v persuading:adj persuasion:n persuasive:adj persuasively:adv unpersuasive:adj' },
  { root: 'censor', bangla: 'সেন্সর করা', rule: null, skills: 'WR', topic: 'media',
    forms: 'censored:adj censoring:v censorship:n uncensored:adj' },
  { root: 'entertain', bangla: 'বিনোদন দেওয়া', rule: null, skills: 'SWLR', topic: 'media',
    forms: 'entertained:adj entertaining:adj entertainment:n entertainer:n' },
];
