import { type RawWordFamily } from './schema';

/**
 * Health, food, sport, family and feeling — the Speaking Part 1 and Part 2
 * band, where the words are common and the marks are lost to grammar rather
 * than to vocabulary.
 *
 * The point of the families here is the **adjective-to-adverb step**, which is
 * where a fluent-sounding answer is made: `heal → healthy → healthily` lets a
 * candidate say the same thing about a person, a habit and a diet without
 * reaching for a new idea each time.
 */
export const FAMILIES_HEALTH: readonly RawWordFamily[] = [
  { root: 'health', bangla: 'স্বাস্থ্য', rule: null, skills: 'SWLR', topic: 'health',
    forms: 'healthy:adj healthier:adj healthiest:adj healthily:adv unhealthy:adj healthcare:n' },
  { root: 'heal', bangla: 'সুস্থ করা', rule: null, skills: 'SLR', topic: 'health',
    forms: 'healed:adj healing:n healer:n' },
  { root: 'ill', bangla: 'অসুস্থ', rule: 'floss_doubling', skills: 'SWLR', topic: 'health',
    forms: 'illness:n illnesses:n' },
  { root: 'sick', bangla: 'অসুস্থ', rule: 'ck_after_short_vowel', skills: 'SWLR', topic: 'health',
    forms: 'sickness:n sicker:adj sickest:adj sickly:adj' },
  { root: 'disease', bangla: 'রোগ', rule: null, skills: 'SWLR', topic: 'health',
    forms: 'diseased:adj diseases:n' },
  { root: 'infect', bangla: 'সংক্রমিত করা', rule: 'tion_sion', skills: 'WLR', topic: 'health',
    forms: 'infected:adj infecting:v infection:n infections:n infectious:adj disinfect:v' },
  { root: 'medicine', bangla: 'ঔষধ', rule: null, skills: 'SWLR', topic: 'health',
    forms: 'medicines:n medical:adj medically:adv medication:n' },
  { root: 'treat', bangla: 'চিকিৎসা করা', rule: null, skills: 'SWLR', topic: 'health',
    forms: 'treated:adj treating:v treatment:n treatments:n untreated:adj mistreat:v' },
  { root: 'cure', bangla: 'নিরাময় করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'health',
    forms: 'cured:adj curing:v cures:n curable:adj incurable:adj' },
  { root: 'prevent', bangla: 'প্রতিরোধ করা', rule: 'tion_sion', skills: 'SWLR', topic: 'health',
    forms: 'prevented:v preventing:v prevention:n preventive:adj preventable:adj' },
  { root: 'diagnose', bangla: 'রোগ নির্ণয় করা', rule: 'drop_silent_e', skills: 'LR', topic: 'health',
    forms: 'diagnosed:adj diagnosing:v diagnosis:n diagnoses:n diagnostic:adj misdiagnose:v' },
  { root: 'surgery', bangla: 'শল্যচিকিৎসা', rule: 'y_to_i', skills: 'LR', topic: 'health',
    forms: 'surgeries:n surgical:adj surgically:adv surgeon:n' },
  { root: 'patient', bangla: 'রোগী', rule: null, skills: 'SWLR', topic: 'health',
    forms: 'patients:n patiently:adv patience:n impatient:adj impatiently:adv impatience:n' },
  { root: 'nurse', bangla: 'সেবিকা', rule: 'drop_silent_e', skills: 'SLR', topic: 'health',
    forms: 'nursed:v nursing:n nurses:n' },
  { root: 'hospital', bangla: 'হাসপাতাল', rule: null, skills: 'SWLR', topic: 'health',
    forms: 'hospitals:n hospitalise:v hospitalisation:n' },
  { root: 'stress', bangla: 'মানসিক চাপ', rule: 'floss_doubling', skills: 'SWLR', topic: 'health',
    forms: 'stressed:adj stressful:adj stressing:v stresses:n destress:v' },
  { root: 'anxious', bangla: 'উদ্বিগ্ন', rule: null, skills: 'SWLR', topic: 'emotion',
    forms: 'anxiously:adv anxiety:n anxieties:n' },
  { root: 'depress', bangla: 'বিষণ্ণ করা', rule: 'tion_sion', skills: 'SWLR', topic: 'emotion',
    forms: 'depressed:adj depressing:adj depression:n depressive:adj' },
  { root: 'addict', bangla: 'আসক্ত করা', rule: 'tion_sion', skills: 'SWLR', topic: 'health',
    forms: 'addicted:adj addicting:adj addiction:n addictions:n addictive:adj' },
  { root: 'obese', bangla: 'স্থূল', rule: null, skills: 'WR', topic: 'health',
    forms: 'obesity:n overweight:adj underweight:adj' },
  { root: 'nutrition', bangla: 'পুষ্টি', rule: 'tion_sion', skills: 'SWLR', topic: 'food',
    forms: 'nutritional:adj nutritionally:adv nutritious:adj nutrient:n malnutrition:n' },
  { root: 'diet', bangla: 'খাদ্যাভ্যাস', rule: null, skills: 'SWLR', topic: 'food',
    forms: 'diets:n dietary:adj dieting:n dietician:n' },
  { root: 'hygiene', bangla: 'স্বাস্থ্যবিধি', rule: null, skills: 'WLR', topic: 'health',
    forms: 'hygienic:adj hygienically:adv unhygienic:adj' },
  { root: 'immune', bangla: 'রোগ প্রতিরোধক', rule: 'drop_silent_e', skills: 'WR', topic: 'health',
    forms: 'immunity:n immunise:v immunisation:n' },
  { root: 'vaccine', bangla: 'টিকা', rule: 'drop_silent_e', skills: 'LR', topic: 'health',
    forms: 'vaccines:n vaccinate:v vaccinated:adj vaccination:n' },
  { root: 'exercise', bangla: 'ব্যায়াম', rule: 'drop_silent_e', skills: 'SWLR', topic: 'sport',
    forms: 'exercised:v exercising:v exercises:n' },
  { root: 'fit', bangla: 'সুস্থ', rule: 'doubling_1_1_1', skills: 'SWLR', topic: 'sport',
    forms: 'fitted:v fitting:adj fitter:adj fittest:adj fitness:n unfit:adj' },
  { root: 'strong', bangla: 'শক্তিশালী', rule: null, skills: 'SWLR', topic: 'sport',
    forms: 'stronger:adj strongest:adj strongly:adv strength:n strengthen:v' },
  { root: 'weak', bangla: 'দুর্বল', rule: null, skills: 'SWLR', topic: 'health',
    forms: 'weaker:adj weakest:adj weakly:adv weakness:n weaknesses:n weaken:v' },
  { root: 'tire', bangla: 'ক্লান্ত করা', rule: 'drop_silent_e', skills: 'SLR', topic: 'health',
    forms: 'tired:adj tiring:adj tireless:adj tirelessly:adv untiring:adj' },
  { root: 'relax', bangla: 'বিশ্রাম নেওয়া', rule: 'plural_es', skills: 'SWLR', topic: 'health',
    forms: 'relaxed:adj relaxes:v relaxing:adj relaxation:n' },
  { root: 'sleep', bangla: 'ঘুমানো', rule: null, skills: 'SWLR', topic: 'health',
    forms: 'sleeping:adj sleepy:adj sleepless:adj slept:v oversleep:v' },

  { root: 'food', bangla: 'খাদ্য', rule: null, skills: 'SWLR', topic: 'food',
    forms: 'foods:n foodstuff:n seafood:n' },
  { root: 'eat', bangla: 'খাওয়া', rule: null, skills: 'SWLR', topic: 'food',
    forms: 'eaten:v eating:n eater:n ate:v overeat:v' },
  { root: 'cook', bangla: 'রান্না করা', rule: null, skills: 'SWLR', topic: 'food',
    forms: 'cooked:adj cooking:n cooker:n uncooked:adj overcook:v' },
  { root: 'taste', bangla: 'স্বাদ', rule: 'drop_silent_e', skills: 'SWLR', topic: 'food',
    forms: 'tasted:v tasting:n tasty:adj tasteless:adj distasteful:adj' },
  { root: 'hunger', bangla: 'ক্ষুধা', rule: null, skills: 'SWLR', topic: 'food',
    forms: 'hungry:adj hungrier:adj hungriest:adj hungrily:adv' },
  { root: 'thirst', bangla: 'তৃষ্ণা', rule: null, skills: 'SLR', topic: 'food',
    forms: 'thirsty:adj thirstier:adj thirstily:adv' },
  { root: 'vegetable', bangla: 'সবজি', rule: null, skills: 'SWLR', topic: 'food',
    forms: 'vegetables:n vegetarian:n vegetation:n vegan:n' },
  { root: 'fresh', bangla: 'তাজা', rule: null, skills: 'SWLR', topic: 'food',
    forms: 'fresher:adj freshest:adj freshly:adv freshness:n refresh:v' },
  { root: 'process', bangla: 'প্রক্রিয়াজাত করা', rule: 'plural_es', skills: 'SWLR', topic: 'food',
    forms: 'processed:adj processing:n processes:n processor:n unprocessed:adj' },
  { root: 'restaurant', bangla: 'রেস্তোরাঁ', rule: null, skills: 'SLR', topic: 'food',
    forms: 'restaurants:n cafe:n canteen:n' },
  { root: 'recipe', bangla: 'রন্ধনপ্রণালী', rule: null, skills: 'SLR', topic: 'food',
    forms: 'recipes:n ingredient:n ingredients:n' },

  { root: 'sport', bangla: 'খেলাধুলা', rule: null, skills: 'SWLR', topic: 'sport',
    forms: 'sports:n sporting:adj sporty:adj sportsman:n sportsmanship:n' },
  { root: 'play', bangla: 'খেলা', rule: null, skills: 'SWLR', topic: 'sport',
    forms: 'played:v playing:n player:n players:n playful:adj playfully:adv playground:n' },
  { root: 'win', bangla: 'জেতা', rule: 'doubling_1_1_1', skills: 'SWLR', topic: 'sport',
    forms: 'winning:adj winner:n winners:n won:v' },
  { root: 'lose', bangla: 'হারা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'sport',
    forms: 'losing:adj loser:n loss:n losses:n lost:adj' },
  { root: 'team', bangla: 'দল', rule: null, skills: 'SWLR', topic: 'sport',
    forms: 'teams:n teamwork:n teammate:n' },
  { root: 'coach', bangla: 'প্রশিক্ষক', rule: 'plural_es', skills: 'SLR', topic: 'sport',
    forms: 'coached:v coaching:n coaches:n' },
  { root: 'athlete', bangla: 'ক্রীড়াবিদ', rule: null, skills: 'WLR', topic: 'sport',
    forms: 'athletes:n athletic:adj athletically:adv athletics:n' },
  { root: 'champion', bangla: 'বিজয়ী', rule: null, skills: 'SLR', topic: 'sport',
    forms: 'champions:n championship:n' },

  { root: 'family', bangla: 'পরিবার', rule: 'y_to_i', skills: 'SWLR', topic: 'family',
    forms: 'families:n familiar:adj familiarly:adv familiarity:n unfamiliar:adj' },
  { root: 'parent', bangla: 'অভিভাবক', rule: null, skills: 'SWLR', topic: 'family',
    forms: 'parents:n parental:adj parenting:n parenthood:n grandparent:n' },
  { root: 'child', bangla: 'শিশু', rule: null, skills: 'SWLR', topic: 'family',
    forms: 'children:n childhood:n childish:adj childishly:adv childlike:adj childcare:n' },
  { root: 'marry', bangla: 'বিয়ে করা', rule: 'y_to_i', skills: 'SWLR', topic: 'family',
    forms: 'married:adj marries:v marrying:v marriage:n unmarried:adj remarry:v' },
  { root: 'friend', bangla: 'বন্ধু', rule: 'i_before_e', skills: 'SWLR', topic: 'family',
    forms: 'friends:n friendly:adj friendlier:adj friendship:n unfriendly:adj befriend:v' },
  { root: 'neighbour', bangla: 'প্রতিবেশী', rule: null, skills: 'SWLR', topic: 'family',
    forms: 'neighbours:n neighbouring:adj neighbourhood:n' },
  { root: 'care', bangla: 'যত্ন নেওয়া', rule: 'drop_silent_e', skills: 'SWLR', topic: 'family',
    forms: 'cared:v caring:adj careful:adj carefully:adv careless:adj carelessly:adv carer:n' },
  { root: 'love', bangla: 'ভালোবাসা', rule: 'no_final_v', skills: 'SWLR', topic: 'emotion',
    forms: 'loved:adj loving:adj lovely:adj lover:n loveless:adj unloved:adj' },
  { root: 'happy', bangla: 'সুখী', rule: 'y_to_i', skills: 'SWLR', topic: 'emotion',
    forms: 'happier:adj happiest:adj happily:adv happiness:n unhappy:adj unhappiness:n' },
  { root: 'sad', bangla: 'দুঃখিত', rule: 'doubling_1_1_1', skills: 'SWLR', topic: 'emotion',
    forms: 'sadder:adj saddest:adj sadly:adv sadness:n sadden:v' },
  { root: 'anger', bangla: 'রাগ', rule: null, skills: 'SWLR', topic: 'emotion',
    forms: 'angry:adj angrier:adj angriest:adj angrily:adv' },
  { root: 'fear', bangla: 'ভয়', rule: null, skills: 'SWLR', topic: 'emotion',
    forms: 'feared:adj fearing:v fearful:adj fearfully:adv fearless:adj fearlessly:adv' },
  { root: 'hope', bangla: 'আশা করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'emotion',
    forms: 'hoped:v hoping:v hopeful:adj hopefully:adv hopeless:adj hopelessly:adv' },
  { root: 'confide', bangla: 'বিশ্বাস করে বলা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'emotion',
    forms: 'confided:v confiding:v confidence:n confident:adj confidently:adv confidential:adj unconfident:adj' },
  { root: 'proud', bangla: 'গর্বিত', rule: null, skills: 'SWLR', topic: 'emotion',
    forms: 'prouder:adj proudest:adj proudly:adv pride:n' },
  { root: 'surprise', bangla: 'অবাক করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'emotion',
    forms: 'surprised:adj surprising:adj surprisingly:adv surprises:n unsurprising:adj' },
  { root: 'excite', bangla: 'উত্তেজিত করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'emotion',
    forms: 'excited:adj exciting:adj excitedly:adv excitement:n unexciting:adj' },
  { root: 'bore', bangla: 'বিরক্ত করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'emotion',
    forms: 'bored:adj boring:adj boredom:n' },
  { root: 'comfort', bangla: 'স্বস্তি', rule: null, skills: 'SWLR', topic: 'emotion',
    forms: 'comforted:adj comforting:adj comfortable:adj comfortably:adv uncomfortable:adj discomfort:n' },
  { root: 'satisfy', bangla: 'সন্তুষ্ট করা', rule: 'y_to_i', skills: 'SWLR', topic: 'emotion',
    forms: 'satisfied:adj satisfies:v satisfying:adj satisfaction:n unsatisfied:adj dissatisfaction:n' },
];
