import { type RawWordFamily } from './schema';

/**
 * Technology, travel, the city, and the connective vocabulary of argument and
 * change — the last of which is not a topic at all but the machinery every
 * Task 1 report and Task 2 essay runs on.
 *
 * `increase`, `decline`, `fluctuate`, `significant`: these are the words a Task
 * 1 answer is graded on, and the families here exist so a candidate can say
 * *rose sharply* twice without writing the word *rose* twice.
 */
export const FAMILIES_MODERN: readonly RawWordFamily[] = [
  { root: 'technology', bangla: 'প্রযুক্তি', rule: 'y_to_i', skills: 'SWLR', topic: 'technology',
    forms: 'technologies:n technological:adj technologically:adv technologist:n technical:adj technically:adv' },
  { root: 'compute', bangla: 'গণনা করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'technology',
    forms: 'computed:v computing:n computer:n computers:n computational:adj' },
  { root: 'digit', bangla: 'অঙ্ক', rule: null, skills: 'SWLR', topic: 'technology',
    forms: 'digits:n digital:adj digitally:adv digitise:v digitisation:n' },
  { root: 'machine', bangla: 'যন্ত্র', rule: null, skills: 'SWLR', topic: 'technology',
    forms: 'machines:n machinery:n machinist:n' },
  { root: 'automate', bangla: 'স্বয়ংক্রিয় করা', rule: 'drop_silent_e', skills: 'WR', topic: 'technology',
    forms: 'automated:adj automating:v automation:n automatic:adj automatically:adv' },
  { root: 'innovate', bangla: 'উদ্ভাবন করা', rule: 'drop_silent_e', skills: 'SWR', topic: 'technology',
    forms: 'innovated:v innovating:v innovation:n innovations:n innovative:adj innovator:n' },
  { root: 'develop', bangla: 'উন্নয়ন করা', rule: null, skills: 'SWLR', topic: 'technology',
    forms: 'developed:adj developing:adj development:n developments:n developer:n underdeveloped:adj redevelop:v' },
  { root: 'design', bangla: 'নকশা করা', rule: 'silent_letters', skills: 'SWLR', topic: 'technology',
    forms: 'designed:adj designing:v designer:n designs:n redesign:v' },
  { root: 'engine', bangla: 'ইঞ্জিন', rule: null, skills: 'SWLR', topic: 'technology',
    forms: 'engines:n engineer:n engineering:n engineered:adj' },
  { root: 'network', bangla: 'নেটওয়ার্ক', rule: null, skills: 'SWLR', topic: 'technology',
    forms: 'networked:adj networking:n networks:n' },
  { root: 'connect', bangla: 'সংযোগ করা', rule: 'tion_sion', skills: 'SWLR', topic: 'communication',
    forms: 'connected:adj connecting:adj connection:n connections:n disconnect:v interconnected:adj' },
  { root: 'access', bangla: 'প্রবেশাধিকার', rule: 'plural_es', skills: 'SWLR', topic: 'technology',
    forms: 'accessed:v accessing:v accesses:n accessible:adj accessibility:n inaccessible:adj' },
  { root: 'encrypt', bangla: 'সংকেতায়িত করা', rule: 'tion_sion', skills: 'WR', topic: 'technology',
    forms: 'encrypted:adj encrypting:v encryption:n decrypt:v' },
  { root: 'load', bangla: 'বোঝাই করা', rule: null, skills: 'LR', topic: 'technology',
    forms: 'loaded:adj loading:n upload:v download:v overload:v unload:v' },
  { root: 'operate', bangla: 'পরিচালনা করা', rule: 'drop_silent_e', skills: 'WLR', topic: 'technology',
    forms: 'operated:adj operating:adj operation:n operations:n operational:adj operator:n inoperable:adj' },
  { root: 'function', bangla: 'কাজ করা', rule: 'tion_sion', skills: 'WLR', topic: 'technology',
    forms: 'functioned:v functioning:adj functional:adj functionally:adv functions:n dysfunctional:adj' },
  { root: 'device', bangla: 'যন্ত্র', rule: 'soft_c', skills: 'SWLR', topic: 'technology',
    forms: 'devices:n devise:v devised:adj' },
  { root: 'screen', bangla: 'পর্দা', rule: null, skills: 'SLR', topic: 'technology',
    forms: 'screened:v screening:n screens:n' },
  { root: 'programme', bangla: 'কর্মসূচি', rule: 'drop_silent_e', skills: 'SLR', topic: 'technology',
    forms: 'programmes:n programming:n programmer:n programmed:adj' },
  { root: 'artificial', bangla: 'কৃত্রিম', rule: null, skills: 'SWR', topic: 'technology',
    forms: 'artificially:adv artifice:n' },

  { root: 'communicate', bangla: 'যোগাযোগ করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'communication',
    forms: 'communicated:v communicating:v communication:n communications:n communicative:adj miscommunication:n' },
  { root: 'converse', bangla: 'কথোপকথন করা', rule: 'tion_sion', skills: 'SL', topic: 'communication',
    forms: 'conversed:v conversing:v conversation:n conversations:n conversational:adj' },
  { root: 'discuss', bangla: 'আলোচনা করা', rule: 'tion_sion', skills: 'SWLR', topic: 'communication',
    forms: 'discussed:v discussing:v discussion:n discussions:n' },
  { root: 'argue', bangla: 'যুক্তি দেখানো', rule: 'drop_silent_e', skills: 'SWR', topic: 'argument',
    forms: 'argued:v arguing:v argument:n arguments:n arguable:adj arguably:adv' },
  { root: 'agree', bangla: 'একমত হওয়া', rule: null, skills: 'SWLR', topic: 'argument',
    forms: 'agreed:adj agreeing:v agreement:n agreements:n disagree:v disagreement:n agreeable:adj' },
  { root: 'oppose', bangla: 'বিরোধিতা করা', rule: 'drop_silent_e', skills: 'SWR', topic: 'argument',
    forms: 'opposed:adj opposing:adj opposition:n opposite:adj oppositional:adj' },
  { root: 'claim', bangla: 'দাবি করা', rule: null, skills: 'WR', topic: 'argument',
    forms: 'claimed:adj claiming:v claims:n claimant:n unclaimed:adj' },
  { root: 'suggest', bangla: 'পরামর্শ দেওয়া', rule: 'tion_sion', skills: 'SWLR', topic: 'argument',
    forms: 'suggested:adj suggesting:v suggestion:n suggestions:n suggestive:adj' },
  { root: 'consider', bangla: 'বিবেচনা করা', rule: null, skills: 'SWLR', topic: 'argument',
    forms: 'considered:adj considering:v consideration:n considerable:adj considerably:adv inconsiderate:adj' },
  { root: 'assume', bangla: 'ধরে নেওয়া', rule: 'drop_silent_e', skills: 'WR', topic: 'argument',
    forms: 'assumed:adj assuming:v assumption:n assumptions:n' },
  { root: 'imply', bangla: 'ইঙ্গিত করা', rule: 'y_to_i', skills: 'WR', topic: 'argument',
    forms: 'implied:adj implies:v implying:v implication:n implications:n' },
  { root: 'emphasise', bangla: 'জোর দেওয়া', rule: 'drop_silent_e', skills: 'SWR', topic: 'argument',
    forms: 'emphasised:adj emphasising:v emphasis:n emphatic:adj emphatically:adv' },
  { root: 'contrast', bangla: 'বৈসাদৃশ্য', rule: null, skills: 'WR', topic: 'argument',
    forms: 'contrasted:v contrasting:adj contrasts:n contrastive:adj' },
  { root: 'compare', bangla: 'তুলনা করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'argument',
    forms: 'compared:v comparing:v comparison:n comparisons:n comparable:adj comparatively:adv incomparable:adj' },
  { root: 'differ', bangla: 'ভিন্ন হওয়া', rule: null, skills: 'SWLR', topic: 'argument',
    forms: 'differed:v differing:adj different:adj differently:adv difference:n differences:n indifferent:adj' },
  { root: 'similar', bangla: 'অনুরূপ', rule: null, skills: 'SWLR', topic: 'argument',
    forms: 'similarly:adv similarity:n similarities:n dissimilar:adj' },
  { root: 'signify', bangla: 'নির্দেশ করা', rule: 'y_to_i', skills: 'WR', topic: 'argument',
    forms: 'signified:v signifies:v significant:adj significantly:adv significance:n insignificant:adj' },
  { root: 'relate', bangla: 'সম্পর্কিত করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'argument',
    forms: 'related:adj relating:v relation:n relations:n relationship:n relative:adj relatively:adv unrelated:adj' },
  { root: 'cause', bangla: 'কারণ', rule: 'drop_silent_e', skills: 'SWLR', topic: 'argument',
    forms: 'caused:v causing:v causes:n causal:adj causation:n' },
  { root: 'result', bangla: 'ফলাফল', rule: null, skills: 'SWLR', topic: 'argument',
    forms: 'resulted:v resulting:adj results:n resultant:adj' },
  { root: 'effect', bangla: 'প্রভাব', rule: null, skills: 'SWLR', topic: 'argument',
    forms: 'effects:n effective:adj effectively:adv effectiveness:n ineffective:adj' },
  { root: 'affect', bangla: 'প্রভাবিত করা', rule: null, skills: 'SWLR', topic: 'argument',
    forms: 'affected:adj affecting:adj affects:v unaffected:adj' },
  { root: 'solve', bangla: 'সমাধান করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'argument',
    forms: 'solved:adj solving:v solution:n solutions:n solvable:adj unsolved:adj resolve:v' },
  { root: 'problem', bangla: 'সমস্যা', rule: null, skills: 'SWLR', topic: 'argument',
    forms: 'problems:n problematic:adj problematically:adv' },

  { root: 'increase', bangla: 'বৃদ্ধি পাওয়া', rule: 'drop_silent_e', skills: 'SWLR', topic: 'change',
    forms: 'increased:adj increasing:adj increasingly:adv increases:n' },
  { root: 'decrease', bangla: 'হ্রাস পাওয়া', rule: 'drop_silent_e', skills: 'WLR', topic: 'change',
    forms: 'decreased:adj decreasing:adj decreasingly:adv decreases:n' },
  { root: 'decline', bangla: 'কমে যাওয়া', rule: 'drop_silent_e', skills: 'WLR', topic: 'change',
    forms: 'declined:adj declining:adj declines:n' },
  { root: 'rise', bangla: 'ওঠা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'change',
    forms: 'rising:adj risen:v rose:v rises:n' },
  { root: 'fall', bangla: 'পড়া', rule: 'floss_doubling', skills: 'SWLR', topic: 'change',
    forms: 'fallen:adj falling:adj falls:n fell:v downfall:n' },
  { root: 'fluctuate', bangla: 'ওঠানামা করা', rule: 'drop_silent_e', skills: 'WR', topic: 'change',
    forms: 'fluctuated:v fluctuating:adj fluctuation:n fluctuations:n' },
  { root: 'stable', bangla: 'স্থিতিশীল', rule: 'drop_silent_e', skills: 'WLR', topic: 'change',
    forms: 'stably:adv stability:n stabilise:v unstable:adj instability:n' },
  { root: 'steady', bangla: 'স্থির', rule: 'y_to_i', skills: 'WLR', topic: 'change',
    forms: 'steadied:v steadier:adj steadily:adv unsteady:adj' },
  { root: 'sharp', bangla: 'তীব্র', rule: null, skills: 'WLR', topic: 'change',
    forms: 'sharper:adj sharpest:adj sharply:adv sharpen:v sharpness:n' },
  { root: 'gradual', bangla: 'ক্রমশ', rule: null, skills: 'WLR', topic: 'change',
    forms: 'gradually:adv gradient:n' },
  { root: 'rapid', bangla: 'দ্রুত', rule: null, skills: 'SWLR', topic: 'change',
    forms: 'rapidly:adv rapidity:n rapids:n' },
  { root: 'slow', bangla: 'ধীর', rule: null, skills: 'SWLR', topic: 'change',
    forms: 'slowed:v slower:adj slowest:adj slowly:adv slowdown:n' },
  { root: 'expand', bangla: 'সম্প্রসারিত করা', rule: 'tion_sion', skills: 'WLR', topic: 'change',
    forms: 'expanded:adj expanding:adj expansion:n expansive:adj' },
  { root: 'reduce', bangla: 'কমানো', rule: 'drop_silent_e', skills: 'SWLR', topic: 'change',
    forms: 'reduced:adj reducing:v reduction:n reductions:n irreducible:adj' },
  { root: 'improve', bangla: 'উন্নত করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'change',
    forms: 'improved:adj improving:adj improvement:n improvements:n' },
  { root: 'worsen', bangla: 'অবনতি হওয়া', rule: null, skills: 'SWLR', topic: 'change',
    forms: 'worsened:adj worsening:adj worse:adj worst:adj' },
  { root: 'transform', bangla: 'রূপান্তর করা', rule: 'tion_sion', skills: 'WR', topic: 'change',
    forms: 'transformed:adj transforming:adj transformation:n transformations:n transformative:adj' },
  { root: 'replace', bangla: 'প্রতিস্থাপন করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'change',
    forms: 'replaced:adj replacing:v replacement:n replacements:n irreplaceable:adj' },

  { root: 'travel', bangla: 'ভ্রমণ করা', rule: null, skills: 'SWLR', topic: 'travel',
    forms: 'travelled:v travelling:n traveller:n travels:n' },
  { root: 'tour', bangla: 'ভ্রমণ', rule: null, skills: 'SWLR', topic: 'travel',
    forms: 'toured:v touring:n tourist:n tourism:n touristic:adj' },
  { root: 'visit', bangla: 'পরিদর্শন করা', rule: null, skills: 'SWLR', topic: 'travel',
    forms: 'visited:v visiting:adj visitor:n visitors:n visits:n' },
  { root: 'journey', bangla: 'যাত্রা', rule: null, skills: 'SWLR', topic: 'travel',
    forms: 'journeys:n journeyed:v' },
  { root: 'transport', bangla: 'পরিবহন', rule: 'tion_sion', skills: 'SWLR', topic: 'travel',
    forms: 'transported:v transporting:v transportation:n transportable:adj' },
  { root: 'commute', bangla: 'যাতায়াত করা', rule: 'drop_silent_e', skills: 'SLR', topic: 'travel',
    forms: 'commuted:v commuting:n commuter:n commuters:n' },
  { root: 'accommodate', bangla: 'থাকার ব্যবস্থা করা', rule: 'drop_silent_e', skills: 'SLR', topic: 'travel',
    forms: 'accommodated:v accommodating:adj accommodation:n' },
  { root: 'destination', bangla: 'গন্তব্য', rule: 'tion_sion', skills: 'SLR', topic: 'travel',
    forms: 'destinations:n destined:adj destiny:n' },
  { root: 'explore', bangla: 'অন্বেষণ করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'travel',
    forms: 'explored:adj exploring:v exploration:n explorer:n unexplored:adj' },
  { root: 'adventure', bangla: 'অভিযান', rule: 'drop_silent_e', skills: 'SLR', topic: 'travel',
    forms: 'adventures:n adventurous:adj adventurously:adv' },

  { root: 'city', bangla: 'শহর', rule: 'y_to_i', skills: 'SWLR', topic: 'city',
    forms: 'cities:n urban:adj urbanise:v urbanisation:n suburban:adj suburb:n' },
  { root: 'build', bangla: 'নির্মাণ করা', rule: null, skills: 'SWLR', topic: 'city',
    forms: 'building:n buildings:n builder:n built:adj rebuild:v' },
  { root: 'construct', bangla: 'নির্মাণ করা', rule: 'tion_sion', skills: 'WLR', topic: 'city',
    forms: 'constructed:adj constructing:v construction:n constructive:adj reconstruct:v' },
  { root: 'house', bangla: 'বাড়ি', rule: 'drop_silent_e', skills: 'SWLR', topic: 'city',
    forms: 'housed:v housing:n houses:n household:n' },
  { root: 'resident', bangla: 'বাসিন্দা', rule: null, skills: 'SWLR', topic: 'city',
    forms: 'residents:n residential:adj residence:n reside:v' },
  { root: 'crowd', bangla: 'ভিড়', rule: null, skills: 'SWLR', topic: 'city',
    forms: 'crowded:adj crowding:v crowds:n overcrowded:adj overcrowding:n' },
  { root: 'traffic', bangla: 'যানজট', rule: null, skills: 'SWLR', topic: 'city',
    forms: 'trafficking:n congested:adj congestion:n' },
  { root: 'infrastructure', bangla: 'অবকাঠামো', rule: null, skills: 'WR', topic: 'city',
    forms: 'infrastructures:n structure:n structural:adj structurally:adv' },
  { root: 'facility', bangla: 'সুবিধা', rule: 'y_to_i', skills: 'SWLR', topic: 'city',
    forms: 'facilities:n facilitate:v facilitator:n' },
  { root: 'space', bangla: 'স্থান', rule: 'soft_c', skills: 'SWLR', topic: 'city',
    forms: 'spaced:adj spacing:n spaces:n spacious:adj' },
];
