import { type RawWordFamily } from './schema';

/**
 * Work, the economy and money — Speaking Part 1 and Part 3 territory, and the
 * source of most Task 1 report vocabulary.
 *
 * Several roots here carry a **negation the learner needs and the dictionary
 * buries**: `employ → unemployed → unemployment` is a Task 2 chain a candidate
 * uses in every second essay, and `unemployment` is one of the most common
 * misspellings in the band-5 scripts this course was built from.
 */
export const FAMILIES_WORK: readonly RawWordFamily[] = [
  { root: 'employ', bangla: 'নিয়োগ করা', rule: null, skills: 'SWLR', topic: 'work',
    forms: 'employed:adj employing:v employer:n employee:n employment:n unemployed:adj unemployment:n' },
  { root: 'work', bangla: 'কাজ করা', rule: null, skills: 'SWLR', topic: 'work',
    forms: 'worked:v working:adj worker:n workers:n workforce:n workplace:n overwork:v' },
  { root: 'profession', bangla: 'পেশা', rule: 'tion_sion', skills: 'SWLR', topic: 'work',
    forms: 'professions:n professional:adj professionally:adv professionalism:n unprofessional:adj' },
  { root: 'career', bangla: 'কর্মজীবন', rule: null, skills: 'SWLR', topic: 'work',
    forms: 'careers:n careerist:n' },
  { root: 'apply', bangla: 'আবেদন করা', rule: 'y_to_i', skills: 'SWLR', topic: 'work',
    forms: 'applied:adj applies:v applying:v application:n applications:n applicant:n applicable:adj' },
  { root: 'recruit', bangla: 'নিয়োগ করা', rule: null, skills: 'LR', topic: 'work',
    forms: 'recruited:v recruiting:n recruitment:n recruiter:n' },
  { root: 'promote', bangla: 'পদোন্নতি দেওয়া', rule: 'drop_silent_e', skills: 'SWLR', topic: 'work',
    forms: 'promoted:v promoting:v promotion:n promotional:adj' },
  { root: 'retire', bangla: 'অবসর নেওয়া', rule: 'drop_silent_e', skills: 'SWLR', topic: 'work',
    forms: 'retired:adj retiring:adj retirement:n' },
  { root: 'manage', bangla: 'পরিচালনা করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'work',
    forms: 'managed:v managing:adj management:n manager:n managerial:adj unmanageable:adj mismanage:v' },
  { root: 'organise', bangla: 'সংগঠিত করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'work',
    forms: 'organised:adj organising:v organisation:n organisations:n organiser:n disorganised:adj reorganise:v' },
  { root: 'lead', bangla: 'নেতৃত্ব দেওয়া', rule: null, skills: 'SWLR', topic: 'work',
    forms: 'leading:adj leader:n leaders:n leadership:n led:v misleading:adj' },
  { root: 'supervise', bangla: 'তত্ত্বাবধান করা', rule: 'drop_silent_e', skills: 'LR', topic: 'work',
    forms: 'supervised:adj supervising:v supervision:n supervisor:n unsupervised:adj' },
  { root: 'colleague', bangla: 'সহকর্মী', rule: null, skills: 'SL', topic: 'work',
    forms: 'colleagues:n collaborate:v collaboration:n collaborative:adj' },
  { root: 'produce', bangla: 'উৎপাদন করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'work',
    forms: 'produced:v producing:v production:n productive:adj productivity:n producer:n unproductive:adj' },
  { root: 'perform', bangla: 'সম্পাদন করা', rule: null, skills: 'SWLR', topic: 'work',
    forms: 'performed:v performing:adj performance:n performances:n performer:n underperform:v' },
  { root: 'skill', bangla: 'দক্ষতা', rule: 'floss_doubling', skills: 'SWLR', topic: 'work',
    forms: 'skilled:adj skills:n skilful:adj skilfully:adv unskilled:adj' },
  { root: 'train', bangla: 'প্রশিক্ষণ দেওয়া', rule: null, skills: 'SWLR', topic: 'work',
    forms: 'trained:adj training:n trainee:n trainer:n untrained:adj retrain:v' },
  { root: 'experience', bangla: 'অভিজ্ঞতা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'work',
    forms: 'experienced:adj experiencing:v experiences:n inexperienced:adj' },
  { root: 'responsible', bangla: 'দায়িত্বশীল', rule: 'able_ible', skills: 'SWLR', topic: 'work',
    forms: 'responsibly:adv responsibility:n responsibilities:n irresponsible:adj irresponsibly:adv' },
  { root: 'reliable', bangla: 'নির্ভরযোগ্য', rule: 'able_ible', skills: 'SWLR', topic: 'work',
    forms: 'reliably:adv reliability:n unreliable:adj rely:v reliance:n' },
  { root: 'salary', bangla: 'বেতন', rule: 'y_to_i', skills: 'SLR', topic: 'money',
    forms: 'salaries:n salaried:adj' },
  { root: 'wage', bangla: 'মজুরি', rule: null, skills: 'WLR', topic: 'money',
    forms: 'wages:n underpaid:adj overpaid:adj' },
  { root: 'earn', bangla: 'উপার্জন করা', rule: null, skills: 'SWLR', topic: 'money',
    forms: 'earned:adj earning:n earnings:n earner:n' },
  { root: 'pay', bangla: 'পরিশোধ করা', rule: null, skills: 'SWLR', topic: 'money',
    forms: 'paid:adj paying:adj payment:n payments:n payable:adj repay:v unpaid:adj' },
  { root: 'afford', bangla: 'সামর্থ্য থাকা', rule: null, skills: 'SWLR', topic: 'money',
    forms: 'afforded:v affording:v affordable:adj affordability:n unaffordable:adj' },
  { root: 'expense', bangla: 'ব্যয়', rule: 'drop_silent_e', skills: 'SWLR', topic: 'money',
    forms: 'expenses:n expensive:adj expensively:adv inexpensive:adj' },
  { root: 'cost', bangla: 'খরচ', rule: null, skills: 'SWLR', topic: 'money',
    forms: 'costing:n costly:adj costs:n' },
  { root: 'price', bangla: 'দাম', rule: 'soft_c', skills: 'SWLR', topic: 'money',
    forms: 'priced:adj pricing:n prices:n priceless:adj overpriced:adj' },
  { root: 'invest', bangla: 'বিনিয়োগ করা', rule: null, skills: 'WLR', topic: 'money',
    forms: 'invested:v investing:n investment:n investments:n investor:n' },
  { root: 'profit', bangla: 'লাভ', rule: null, skills: 'WLR', topic: 'money',
    forms: 'profited:v profitable:adj profitably:adv profits:n unprofitable:adj nonprofit:adj' },
  { root: 'benefit', bangla: 'সুবিধা', rule: null, skills: 'SWLR', topic: 'money',
    forms: 'benefited:v benefiting:v beneficial:adj beneficially:adv beneficiary:n benefits:n' },
  { root: 'economy', bangla: 'অর্থনীতি', rule: 'y_to_i', skills: 'SWLR', topic: 'economy',
    forms: 'economies:n economic:adj economical:adj economically:adv economist:n uneconomic:adj' },
  { root: 'finance', bangla: 'অর্থব্যবস্থা', rule: 'soft_c', skills: 'WLR', topic: 'economy',
    forms: 'financed:v financing:n financial:adj financially:adv financier:n' },
  { root: 'budget', bangla: 'বাজেট', rule: null, skills: 'SWLR', topic: 'money',
    forms: 'budgeted:adj budgeting:n budgets:n budgetary:adj' },
  { root: 'trade', bangla: 'বাণিজ্য', rule: 'drop_silent_e', skills: 'WLR', topic: 'economy',
    forms: 'traded:v trading:n trader:n trades:n' },
  { root: 'export', bangla: 'রপ্তানি করা', rule: null, skills: 'WLR', topic: 'economy',
    forms: 'exported:adj exporting:v exports:n exporter:n' },
  { root: 'import', bangla: 'আমদানি করা', rule: null, skills: 'WLR', topic: 'economy',
    forms: 'imported:adj importing:v imports:n importer:n' },
  { root: 'industry', bangla: 'শিল্প', rule: 'y_to_i', skills: 'SWLR', topic: 'economy',
    forms: 'industries:n industrial:adj industrially:adv industrialise:v industrialisation:n' },
  { root: 'commerce', bangla: 'বাণিজ্য', rule: 'soft_c', skills: 'WR', topic: 'economy',
    forms: 'commercial:adj commercially:adv commercialise:v noncommercial:adj' },
  { root: 'market', bangla: 'বাজার', rule: null, skills: 'SWLR', topic: 'economy',
    forms: 'marketed:v marketing:n markets:n marketplace:n' },
  { root: 'monopoly', bangla: 'একচেটিয়া অধিকার', rule: 'y_to_i', skills: 'WR', topic: 'economy',
    forms: 'monopolies:n monopolise:v monopolistic:adj' },
  { root: 'wealth', bangla: 'সম্পদ', rule: null, skills: 'SWLR', topic: 'money',
    forms: 'wealthy:adj wealthier:adj wealthiest:adj wealthily:adv' },
  { root: 'poor', bangla: 'দরিদ্র', rule: null, skills: 'SWLR', topic: 'money',
    forms: 'poorly:adv poorer:adj poorest:adj poverty:n' },
  { root: 'rich', bangla: 'ধনী', rule: 'plural_es', skills: 'SWLR', topic: 'money',
    forms: 'riches:n richer:adj richest:adj richly:adv enrich:v' },
  { root: 'debt', bangla: 'ঋণ', rule: 'silent_letters', skills: 'WLR', topic: 'money',
    forms: 'debts:n debtor:n indebted:adj' },
  { root: 'borrow', bangla: 'ধার নেওয়া', rule: null, skills: 'SLR', topic: 'money',
    forms: 'borrowed:v borrowing:n borrower:n' },
  { root: 'lend', bangla: 'ধার দেওয়া', rule: null, skills: 'SLR', topic: 'money',
    forms: 'lending:n lender:n lent:v' },
  { root: 'spend', bangla: 'খরচ করা', rule: null, skills: 'SWLR', topic: 'money',
    forms: 'spending:n spender:n spent:v overspend:v' },
  { root: 'tax', bangla: 'কর', rule: 'plural_es', skills: 'SWLR', topic: 'money',
    forms: 'taxed:adj taxes:n taxing:adj taxation:n taxpayer:n untaxed:adj' },
  { root: 'customer', bangla: 'ক্রেতা', rule: null, skills: 'SLR', topic: 'economy',
    forms: 'customers:n custom:n customary:adj' },
  { root: 'client', bangla: 'মক্কেল', rule: null, skills: 'SLR', topic: 'economy',
    forms: 'clients:n clientele:n' },
  { root: 'negotiate', bangla: 'আলোচনা করা', rule: 'drop_silent_e', skills: 'WLR', topic: 'work',
    forms: 'negotiated:v negotiating:v negotiation:n negotiations:n negotiable:adj nonnegotiable:adj' },
  { root: 'contract', bangla: 'চুক্তি', rule: null, skills: 'LR', topic: 'work',
    forms: 'contracted:v contracting:v contracts:n contractual:adj contractor:n' },
  { root: 'deadline', bangla: 'সময়সীমা', rule: null, skills: 'SLR', topic: 'work',
    forms: 'deadlines:n punctual:adj punctuality:n punctually:adv' },
  { root: 'shift', bangla: 'পালা', rule: null, skills: 'SLR', topic: 'work',
    forms: 'shifted:v shifting:adj shifts:n' },
  { root: 'labour', bangla: 'শ্রম', rule: null, skills: 'WLR', topic: 'work',
    forms: 'laboured:adj labouring:n labourer:n laborious:adj' },
  { root: 'strike', bangla: 'ধর্মঘট', rule: 'drop_silent_e', skills: 'LR', topic: 'work',
    forms: 'striking:adj strikes:n struck:v striker:n' },
  { root: 'volunteer', bangla: 'স্বেচ্ছাসেবক', rule: null, skills: 'SWLR', topic: 'work',
    forms: 'volunteered:v volunteering:n volunteers:n voluntary:adj voluntarily:adv' },
  { root: 'entrepreneur', bangla: 'উদ্যোক্তা', rule: null, skills: 'WR', topic: 'economy',
    forms: 'entrepreneurs:n entrepreneurial:adj enterprise:n enterprising:adj' },
];
