import { type RawWordFamily } from './schema';

/**
 * Environment, energy and agriculture — the topic band that produces more
 * Task 2 essays than any other, and the one where a candidate's vocabulary
 * most often collapses into repeating "pollution" six times.
 *
 * The families here are deliberately heavy on **noun/adjective/adverb triples**
 * (`sustain → sustainable → sustainably`), because that is the move that lifts
 * a Task 2 answer: the same idea said a second way without saying the same
 * word.
 */
export const FAMILIES_ENVIRONMENT: readonly RawWordFamily[] = [
  { root: 'environment', bangla: 'পরিবেশ', rule: null, skills: 'SWLR', topic: 'environment',
    forms: 'environmental:adj environmentally:adv environmentalist:n environments:n' },
  { root: 'pollute', bangla: 'দূষিত করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'environment',
    forms: 'polluted:adj polluting:adj pollution:n pollutant:n unpolluted:adj' },
  { root: 'sustain', bangla: 'টিকিয়ে রাখা', rule: null, skills: 'SWR', topic: 'environment',
    forms: 'sustained:adj sustaining:adj sustainable:adj sustainably:adv sustainability:n unsustainable:adj' },
  { root: 'conserve', bangla: 'সংরক্ষণ করা', rule: 'drop_silent_e', skills: 'WR', topic: 'environment',
    forms: 'conserved:v conserving:v conservation:n conservationist:n' },
  { root: 'preserve', bangla: 'সংরক্ষণ করা', rule: 'drop_silent_e', skills: 'WR', topic: 'environment',
    forms: 'preserved:adj preserving:v preservation:n preservative:n' },
  { root: 'protect', bangla: 'রক্ষা করা', rule: 'tion_sion', skills: 'SWLR', topic: 'environment',
    forms: 'protected:adj protecting:v protection:n protective:adj protectively:adv unprotected:adj' },
  { root: 'destroy', bangla: 'ধ্বংস করা', rule: null, skills: 'SWR', topic: 'environment',
    forms: 'destroyed:adj destroying:v destruction:n destructive:adj indestructible:adj' },
  { root: 'damage', bangla: 'ক্ষতি করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'environment',
    forms: 'damaged:adj damaging:adj damages:n undamaged:adj' },
  { root: 'recycle', bangla: 'পুনর্ব্যবহার করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'environment',
    forms: 'recycled:adj recycling:n recyclable:adj' },
  { root: 'waste', bangla: 'অপচয় করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'environment',
    forms: 'wasted:adj wasting:v wasteful:adj wastefully:adv wasteland:n' },
  { root: 'climate', bangla: 'জলবায়ু', rule: null, skills: 'SWLR', topic: 'environment',
    forms: 'climates:n climatic:adj climatically:adv' },
  { root: 'warm', bangla: 'উষ্ণ', rule: null, skills: 'SWLR', topic: 'environment',
    forms: 'warmed:v warming:n warmer:adj warmest:adj warmly:adv warmth:n' },
  { root: 'emit', bangla: 'নির্গত করা', rule: 'doubling_1_1_1', skills: 'WR', topic: 'environment',
    forms: 'emitted:v emitting:v emission:n emissions:n' },
  { root: 'carbon', bangla: 'কার্বন', rule: null, skills: 'WR', topic: 'environment',
    forms: 'carbons:n carbonate:n decarbonise:v' },
  { root: 'nature', bangla: 'প্রকৃতি', rule: 'drop_silent_e', skills: 'SWLR', topic: 'environment',
    forms: 'natural:adj naturally:adv naturalist:n unnatural:adj supernatural:adj' },
  { root: 'wild', bangla: 'বন্য', rule: null, skills: 'SLR', topic: 'environment',
    forms: 'wildly:adv wilder:adj wildest:adj wildlife:n wilderness:n' },
  { root: 'forest', bangla: 'বন', rule: null, skills: 'SWLR', topic: 'environment',
    forms: 'forests:n forested:adj forestry:n deforestation:n reforestation:n' },
  { root: 'extinct', bangla: 'বিলুপ্ত', rule: 'tion_sion', skills: 'WR', topic: 'environment',
    forms: 'extinction:n extinctions:n extinguish:v' },
  { root: 'endanger', bangla: 'বিপন্ন করা', rule: null, skills: 'WR', topic: 'environment',
    forms: 'endangered:adj endangering:v dangerous:adj dangerously:adv danger:n' },
  { root: 'survive', bangla: 'বেঁচে থাকা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'environment',
    forms: 'survived:v surviving:adj survival:n survivor:n' },
  { root: 'habitat', bangla: 'বাসস্থান', rule: null, skills: 'WR', topic: 'environment',
    forms: 'habitats:n inhabit:v inhabitant:n uninhabited:adj' },
  { root: 'species', bangla: 'প্রজাতি', rule: null, skills: 'WR', topic: 'environment',
    forms: 'specific:adj specifically:adv specify:v' },
  { root: 'contaminate', bangla: 'দূষিত করা', rule: 'drop_silent_e', skills: 'WR', topic: 'environment',
    forms: 'contaminated:adj contaminating:v contamination:n contaminant:n uncontaminated:adj' },
  { root: 'toxic', bangla: 'বিষাক্ত', rule: null, skills: 'WR', topic: 'environment',
    forms: 'toxicity:n toxin:n nontoxic:adj' },
  { root: 'green', bangla: 'সবুজ', rule: null, skills: 'SWLR', topic: 'environment',
    forms: 'greener:adj greenest:adj greenery:n greenhouse:n' },
  { root: 'flood', bangla: 'বন্যা', rule: null, skills: 'SWLR', topic: 'environment',
    forms: 'flooded:adj flooding:n floods:n floodwater:n' },
  { root: 'drought', bangla: 'খরা', rule: 'silent_letters', skills: 'WLR', topic: 'environment',
    forms: 'droughts:n dry:adj drier:adj driest:adj' },
  { root: 'erode', bangla: 'ক্ষয় করা', rule: 'drop_silent_e', skills: 'WR', topic: 'environment',
    forms: 'eroded:adj eroding:v erosion:n' },
  { root: 'disaster', bangla: 'দুর্যোগ', rule: null, skills: 'SWLR', topic: 'environment',
    forms: 'disasters:n disastrous:adj disastrously:adv' },
  { root: 'weather', bangla: 'আবহাওয়া', rule: null, skills: 'SWLR', topic: 'environment',
    forms: 'weathered:adj weathering:n weatherproof:adj' },

  { root: 'energy', bangla: 'শক্তি', rule: 'y_to_i', skills: 'SWLR', topic: 'energy',
    forms: 'energies:n energetic:adj energetically:adv energise:v' },
  { root: 'power', bangla: 'ক্ষমতা', rule: null, skills: 'SWLR', topic: 'energy',
    forms: 'powered:adj powering:v powerful:adj powerfully:adv powerless:adj' },
  { root: 'electric', bangla: 'বৈদ্যুতিক', rule: null, skills: 'SWLR', topic: 'energy',
    forms: 'electrical:adj electrically:adv electricity:n electrician:n' },
  { root: 'renew', bangla: 'নবায়ন করা', rule: null, skills: 'SWR', topic: 'energy',
    forms: 'renewed:adj renewing:v renewable:adj renewal:n nonrenewable:adj' },
  { root: 'fuel', bangla: 'জ্বালানি', rule: null, skills: 'SWLR', topic: 'energy',
    forms: 'fuelled:adj fuelling:v fuels:n refuel:v' },
  { root: 'consume', bangla: 'ভোগ করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'energy',
    forms: 'consumed:v consuming:adj consumption:n consumer:n consumers:n' },
  { root: 'efficient', bangla: 'দক্ষ', rule: null, skills: 'SWLR', topic: 'energy',
    forms: 'efficiently:adv efficiency:n inefficient:adj inefficiency:n inefficiently:adv' },
  { root: 'solar', bangla: 'সৌর', rule: null, skills: 'WLR', topic: 'energy',
    forms: 'sun:n sunny:adj sunlight:n sunshine:n' },
  { root: 'nuclear', bangla: 'পারমাণবিক', rule: null, skills: 'WR', topic: 'energy',
    forms: 'nucleus:n nuclei:n' },
  { root: 'generate', bangla: 'উৎপন্ন করা', rule: 'drop_silent_e', skills: 'WLR', topic: 'energy',
    forms: 'generated:v generating:adj generation:n generations:n generator:n' },
  { root: 'store', bangla: 'সঞ্চয় করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'energy',
    forms: 'stored:adj storing:v storage:n stores:n' },
  { root: 'supply', bangla: 'সরবরাহ করা', rule: 'y_to_i', skills: 'SWLR', topic: 'energy',
    forms: 'supplied:v supplies:n supplying:v supplier:n undersupply:n' },
  { root: 'demand', bangla: 'চাহিদা', rule: null, skills: 'SWLR', topic: 'economy',
    forms: 'demanded:v demanding:adj demands:n' },
  { root: 'save', bangla: 'সঞ্চয় করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'energy',
    forms: 'saved:adj saving:n savings:n saver:n lifesaving:adj' },
  { root: 'heat', bangla: 'তাপ', rule: null, skills: 'SWLR', topic: 'energy',
    forms: 'heated:adj heating:n heater:n overheat:v preheat:v' },

  { root: 'agriculture', bangla: 'কৃষি', rule: 'drop_silent_e', skills: 'WR', topic: 'agriculture',
    forms: 'agricultural:adj agriculturally:adv agriculturalist:n' },
  { root: 'farm', bangla: 'খামার', rule: null, skills: 'SWLR', topic: 'agriculture',
    forms: 'farmed:adj farming:n farmer:n farmland:n farmyard:n' },
  { root: 'crop', bangla: 'ফসল', rule: 'doubling_1_1_1', skills: 'SWLR', topic: 'agriculture',
    forms: 'cropped:v cropping:n crops:n cropland:n' },
  { root: 'harvest', bangla: 'ফসল কাটা', rule: null, skills: 'WLR', topic: 'agriculture',
    forms: 'harvested:v harvesting:n harvests:n' },
  { root: 'irrigate', bangla: 'সেচ দেওয়া', rule: 'drop_silent_e', skills: 'WR', topic: 'agriculture',
    forms: 'irrigated:adj irrigating:v irrigation:n' },
  { root: 'fertile', bangla: 'উর্বর', rule: 'drop_silent_e', skills: 'WR', topic: 'agriculture',
    forms: 'fertility:n fertilise:v fertiliser:n infertile:adj' },
  { root: 'grow', bangla: 'বেড়ে ওঠা', rule: null, skills: 'SWLR', topic: 'agriculture',
    forms: 'grew:v growing:adj grown:adj growth:n grower:n outgrow:v overgrown:adj' },
  { root: 'plant', bangla: 'গাছ লাগানো', rule: null, skills: 'SWLR', topic: 'agriculture',
    forms: 'planted:adj planting:n plants:n plantation:n replant:v' },
  { root: 'seed', bangla: 'বীজ', rule: null, skills: 'SLR', topic: 'agriculture',
    forms: 'seeded:adj seeding:n seeds:n seedling:n' },
  { root: 'soil', bangla: 'মাটি', rule: null, skills: 'WLR', topic: 'agriculture',
    forms: 'soiled:adj soils:n topsoil:n' },
  { root: 'organic', bangla: 'জৈব', rule: null, skills: 'SWLR', topic: 'agriculture',
    forms: 'organically:adv inorganic:adj organism:n organisms:n' },
  { root: 'livestock', bangla: 'গবাদি পশু', rule: null, skills: 'R', topic: 'agriculture',
    forms: 'cattle:n herd:n grazing:n' },
  { root: 'rural', bangla: 'গ্রামীণ', rule: null, skills: 'SWLR', topic: 'agriculture',
    forms: 'rurally:adv countryside:n village:n villages:n villager:n' },
  { root: 'yield', bangla: 'উৎপাদন', rule: 'i_before_e', skills: 'WR', topic: 'agriculture',
    forms: 'yielded:v yielding:adj yields:n' },
  { root: 'pesticide', bangla: 'কীটনাশক', rule: null, skills: 'WR', topic: 'agriculture',
    forms: 'pesticides:n pest:n pests:n insecticide:n' },
];
