import { type RawWordFamily } from './schema';

/**
 * Education, science and language — the three topics that carry the most marks
 * in Academic Writing Task 2 and the most predictable Speaking Part 3 prompts.
 *
 * Roots are chosen for **spread, not frequency**. `educate` earns a place
 * because it reaches a noun, an adjective, an adverb, an agent noun and a
 * negation; a commoner word that stops at two forms teaches less about English
 * than a rarer one that reaches six.
 */
export const FAMILIES_LEARNING: readonly RawWordFamily[] = [
  { root: 'educate', bangla: 'শিক্ষা দেওয়া', rule: 'drop_silent_e', skills: 'SWLR', topic: 'education',
    forms: 'educated:adj educating:v education:n educational:adj educationally:adv educator:n uneducated:adj' },
  { root: 'teach', bangla: 'পড়ানো', rule: null, skills: 'SWLR', topic: 'education',
    forms: 'teacher:n teaching:n taught:v teachable:adj' },
  { root: 'learn', bangla: 'শেখা', rule: null, skills: 'SWLR', topic: 'education',
    forms: 'learner:n learning:n learned:adj learnt:v unlearn:v' },
  { root: 'study', bangla: 'অধ্যয়ন করা', rule: 'y_to_i', skills: 'SWLR', topic: 'education',
    forms: 'studies:n studied:v studying:v studious:adj studiously:adv' },
  { root: 'know', bangla: 'জানা', rule: 'silent_letters', skills: 'SWLR', topic: 'education',
    forms: 'knowledge:n knowledgeable:adj knowing:adj knowingly:adv known:adj unknown:adj' },
  { root: 'qualify', bangla: 'যোগ্যতা অর্জন করা', rule: 'y_to_i', skills: 'WR', topic: 'education',
    forms: 'qualified:adj qualifies:v qualifying:adj qualification:n unqualified:adj disqualify:v' },
  { root: 'graduate', bangla: 'স্নাতক হওয়া', rule: 'drop_silent_e', skills: 'SWLR', topic: 'education',
    forms: 'graduated:v graduating:v graduation:n graduates:n undergraduate:n postgraduate:n' },
  { root: 'academy', bangla: 'বিদ্যায়তন', rule: 'y_to_i', skills: 'WR', topic: 'education',
    forms: 'academic:adj academically:adv academies:n academia:n' },
  { root: 'instruct', bangla: 'নির্দেশ দেওয়া', rule: 'tion_sion', skills: 'LR', topic: 'education',
    forms: 'instruction:n instructions:n instructional:adj instructor:n instructive:adj' },
  { root: 'examine', bangla: 'পরীক্ষা করা', rule: 'drop_silent_e', skills: 'LR', topic: 'education',
    forms: 'examined:v examining:v examination:n examiner:n reexamine:v' },
  { root: 'assess', bangla: 'মূল্যায়ন করা', rule: 'tion_sion', skills: 'WR', topic: 'education',
    forms: 'assessed:v assessing:v assessment:n assessor:n reassess:v' },
  { root: 'enrol', bangla: 'ভর্তি হওয়া', rule: 'doubling_1_1_1', skills: 'LR', topic: 'education',
    forms: 'enrolled:v enrolling:v enrolment:n enrolments:n' },
  { root: 'attend', bangla: 'উপস্থিত থাকা', rule: null, skills: 'SLR', topic: 'education',
    forms: 'attended:v attending:v attendance:n attendee:n attentive:adj' },
  { root: 'motivate', bangla: 'অনুপ্রাণিত করা', rule: 'drop_silent_e', skills: 'SW', topic: 'education',
    forms: 'motivated:adj motivating:adj motivation:n motivational:adj unmotivated:adj demotivate:v' },
  { root: 'discipline', bangla: 'শৃঙ্খলা', rule: 'drop_silent_e', skills: 'WR', topic: 'education',
    forms: 'disciplined:adj disciplining:v disciplinary:adj undisciplined:adj' },
  { root: 'curriculum', bangla: 'পাঠ্যক্রম', rule: null, skills: 'WR', topic: 'education',
    forms: 'curricula:n curricular:adj extracurricular:adj' },
  { root: 'lecture', bangla: 'বক্তৃতা', rule: 'drop_silent_e', skills: 'SL', topic: 'education',
    forms: 'lectured:v lecturing:v lecturer:n lectures:n' },
  { root: 'tutor', bangla: 'গৃহশিক্ষক', rule: null, skills: 'SL', topic: 'education',
    forms: 'tutored:v tutoring:n tutorial:n tutors:n' },
  { root: 'scholar', bangla: 'পণ্ডিত', rule: null, skills: 'WR', topic: 'education',
    forms: 'scholarly:adj scholarship:n scholarships:n scholastic:adj' },
  { root: 'literate', bangla: 'শিক্ষিত', rule: null, skills: 'WR', topic: 'education',
    forms: 'literacy:n illiterate:adj illiteracy:n literary:adj' },
  { root: 'intellect', bangla: 'বুদ্ধি', rule: null, skills: 'WR', topic: 'education',
    forms: 'intellectual:adj intellectually:adv intelligence:n intelligent:adj intelligently:adv' },
  { root: 'compete', bangla: 'প্রতিযোগিতা করা', rule: 'drop_silent_e', skills: 'SWR', topic: 'education',
    forms: 'competed:v competing:adj competition:n competitive:adj competitively:adv competitor:n uncompetitive:adj' },
  { root: 'achieve', bangla: 'অর্জন করা', rule: 'i_before_e', skills: 'SWLR', topic: 'education',
    forms: 'achieved:v achieving:v achievement:n achievements:n achievable:adj unachievable:adj' },
  { root: 'succeed', bangla: 'সফল হওয়া', rule: null, skills: 'SWLR', topic: 'education',
    forms: 'succeeded:v succeeding:adj success:n successful:adj successfully:adv unsuccessful:adj' },
  { root: 'fail', bangla: 'ব্যর্থ হওয়া', rule: null, skills: 'SWLR', topic: 'education',
    forms: 'failed:adj failing:adj failure:n failures:n unfailing:adj' },

  { root: 'science', bangla: 'বিজ্ঞান', rule: 'soft_c', skills: 'WR', topic: 'science',
    forms: 'scientific:adj scientifically:adv scientist:n sciences:n unscientific:adj' },
  { root: 'research', bangla: 'গবেষণা', rule: null, skills: 'WLR', topic: 'science',
    forms: 'researched:adj researching:v researcher:n researchers:n' },
  { root: 'analyse', bangla: 'বিশ্লেষণ করা', rule: 'drop_silent_e', skills: 'WR', topic: 'science',
    forms: 'analysed:v analysing:v analysis:n analyses:n analyst:n analytical:adj analytically:adv' },
  { root: 'experiment', bangla: 'পরীক্ষা-নিরীক্ষা', rule: null, skills: 'WLR', topic: 'science',
    forms: 'experimented:v experimenting:v experimental:adj experimentally:adv experimentation:n' },
  { root: 'observe', bangla: 'পর্যবেক্ষণ করা', rule: 'drop_silent_e', skills: 'WLR', topic: 'science',
    forms: 'observed:v observing:v observation:n observations:n observer:n observable:adj unobserved:adj' },
  { root: 'discover', bangla: 'আবিষ্কার করা', rule: null, skills: 'SWLR', topic: 'science',
    forms: 'discovered:v discovering:v discovery:n discoveries:n rediscover:v undiscovered:adj' },
  { root: 'invent', bangla: 'উদ্ভাবন করা', rule: 'tion_sion', skills: 'SWR', topic: 'science',
    forms: 'invented:adj inventing:v invention:n inventions:n inventor:n inventive:adj' },
  { root: 'theory', bangla: 'তত্ত্ব', rule: 'y_to_i', skills: 'WR', topic: 'science',
    forms: 'theories:n theoretical:adj theoretically:adv theorist:n' },
  { root: 'evidence', bangla: 'প্রমাণ', rule: 'soft_c', skills: 'WR', topic: 'science',
    forms: 'evident:adj evidently:adv evidenced:v' },
  { root: 'prove', bangla: 'প্রমাণ করা', rule: 'drop_silent_e', skills: 'SWR', topic: 'science',
    forms: 'proved:v proving:v proof:n proven:adj disprove:v unproven:adj' },
  { root: 'measure', bangla: 'পরিমাপ করা', rule: 'drop_silent_e', skills: 'WLR', topic: 'measurement',
    forms: 'measured:adj measuring:v measurement:n measurements:n measurable:adj immeasurable:adj' },
  { root: 'calculate', bangla: 'গণনা করা', rule: 'drop_silent_e', skills: 'WLR', topic: 'measurement',
    forms: 'calculated:adj calculating:v calculation:n calculations:n calculator:n miscalculate:v' },
  { root: 'estimate', bangla: 'আনুমানিক হিসাব করা', rule: 'drop_silent_e', skills: 'WLR', topic: 'measurement',
    forms: 'estimated:adj estimating:v estimation:n underestimate:v overestimate:v' },
  { root: 'accurate', bangla: 'নির্ভুল', rule: null, skills: 'WLR', topic: 'measurement',
    forms: 'accurately:adv accuracy:n inaccurate:adj inaccuracy:n inaccurately:adv' },
  { root: 'precise', bangla: 'যথাযথ', rule: 'soft_c', skills: 'WR', topic: 'measurement',
    forms: 'precisely:adv precision:n imprecise:adj' },
  { root: 'chemistry', bangla: 'রসায়ন', rule: null, skills: 'R', topic: 'science',
    forms: 'chemical:adj chemicals:n chemically:adv chemist:n' },
  { root: 'biology', bangla: 'জীববিজ্ঞান', rule: null, skills: 'R', topic: 'science',
    forms: 'biological:adj biologically:adv biologist:n' },
  { root: 'physics', bangla: 'পদার্থবিজ্ঞান', rule: null, skills: 'R', topic: 'science',
    forms: 'physical:adj physically:adv physicist:n' },
  { root: 'astronomy', bangla: 'জ্যোতির্বিজ্ঞান', rule: null, skills: 'R', topic: 'science',
    forms: 'astronomer:n astronomical:adj astronomically:adv' },
  { root: 'genetic', bangla: 'বংশগত', rule: null, skills: 'R', topic: 'science',
    forms: 'genetics:n genetically:adv gene:n genome:n' },
  { root: 'evolve', bangla: 'ক্রমবিকাশ হওয়া', rule: 'drop_silent_e', skills: 'WR', topic: 'science',
    forms: 'evolved:v evolving:adj evolution:n evolutionary:adj' },
  { root: 'hypothesis', bangla: 'অনুকল্প', rule: null, skills: 'R', topic: 'science',
    forms: 'hypotheses:n hypothetical:adj hypothetically:adv hypothesise:v' },
  { root: 'conclude', bangla: 'উপসংহারে আসা', rule: 'drop_silent_e', skills: 'WLR', topic: 'argument',
    forms: 'concluded:v concluding:adj conclusion:n conclusions:n conclusive:adj inconclusive:adj' },
  { root: 'sample', bangla: 'নমুনা', rule: 'drop_silent_e', skills: 'WR', topic: 'measurement',
    forms: 'sampled:v sampling:n samples:n' },
  { root: 'data', bangla: 'উপাত্ত', rule: null, skills: 'WLR', topic: 'measurement',
    forms: 'database:n dataset:n datasets:n' },

  { root: 'language', bangla: 'ভাষা', rule: null, skills: 'SWLR', topic: 'language',
    forms: 'languages:n linguistic:adj linguistically:adv linguist:n bilingual:adj multilingual:adj' },
  { root: 'speak', bangla: 'বলা', rule: null, skills: 'SWLR', topic: 'language',
    forms: 'speaker:n speaking:n spoke:v spoken:adj outspoken:adj unspoken:adj' },
  { root: 'write', bangla: 'লেখা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'language',
    forms: 'writer:n writing:n written:adj wrote:v rewrite:v unwritten:adj' },
  { root: 'read', bangla: 'পড়া', rule: null, skills: 'SWLR', topic: 'language',
    forms: 'reader:n reading:n readable:adj unreadable:adj misread:v proofread:v' },
  { root: 'listen', bangla: 'শোনা', rule: 'silent_letters', skills: 'SWLR', topic: 'language',
    forms: 'listened:v listening:n listener:n listeners:n' },
  { root: 'pronounce', bangla: 'উচ্চারণ করা', rule: 'drop_silent_e', skills: 'SL', topic: 'language',
    forms: 'pronounced:adj pronouncing:v pronunciation:n mispronounce:v' },
  { root: 'translate', bangla: 'অনুবাদ করা', rule: 'drop_silent_e', skills: 'LR', topic: 'language',
    forms: 'translated:adj translating:v translation:n translations:n translator:n untranslatable:adj' },
  { root: 'grammar', bangla: 'ব্যাকরণ', rule: null, skills: 'WR', topic: 'language',
    forms: 'grammatical:adj grammatically:adv ungrammatical:adj' },
  { root: 'spell', bangla: 'বানান করা', rule: 'floss_doubling', skills: 'WL', topic: 'language',
    forms: 'spelled:v spelling:n spellings:n misspell:v misspelling:n' },
  { root: 'vocabulary', bangla: 'শব্দভান্ডার', rule: 'y_to_i', skills: 'SWLR', topic: 'language',
    forms: 'vocabularies:n vocal:adj vocally:adv' },
  { root: 'express', bangla: 'প্রকাশ করা', rule: 'tion_sion', skills: 'SWLR', topic: 'language',
    forms: 'expressed:v expressing:v expression:n expressions:n expressive:adj inexpressible:adj' },
  { root: 'describe', bangla: 'বর্ণনা করা', rule: 'drop_silent_e', skills: 'SWLR', topic: 'language',
    forms: 'described:v describing:v description:n descriptions:n descriptive:adj indescribable:adj' },
  { root: 'explain', bangla: 'ব্যাখ্যা করা', rule: 'tion_sion', skills: 'SWLR', topic: 'language',
    forms: 'explained:v explaining:v explanation:n explanations:n explanatory:adj unexplained:adj' },
  { root: 'define', bangla: 'সংজ্ঞা দেওয়া', rule: 'drop_silent_e', skills: 'WR', topic: 'language',
    forms: 'defined:adj defining:adj definition:n definitions:n definite:adj definitely:adv undefined:adj' },
  { root: 'interpret', bangla: 'ব্যাখ্যা করা', rule: 'tion_sion', skills: 'LR', topic: 'language',
    forms: 'interpreted:v interpreting:v interpretation:n interpreter:n misinterpret:v' },
  { root: 'summarise', bangla: 'সারসংক্ষেপ করা', rule: 'drop_silent_e', skills: 'WR', topic: 'language',
    forms: 'summarised:v summarising:v summary:n summaries:n' },
  { root: 'quote', bangla: 'উদ্ধৃত করা', rule: 'drop_silent_e', skills: 'WR', topic: 'language',
    forms: 'quoted:v quoting:v quotation:n quotations:n' },
  { root: 'phrase', bangla: 'বাক্যাংশ', rule: 'drop_silent_e', skills: 'SWLR', topic: 'language',
    forms: 'phrased:v phrasing:n phrases:n rephrase:v' },
];
