import { type IRawVocabularyGroup } from './schema';

/**
 * Where things are, and how they move.
 *
 * Speaking Part 1 asks about a hometown and Part 2 asks about a place, and both
 * are answered with the same eight words unless a candidate has these. `remote`
 * and `congested` do in one word what a Band 5 answer does in a clause.
 */
export const VOCAB_PLACE: IRawVocabularyGroup = {
  topic: 'place',
  entries: [
    'remote:adj = isolated, far-flung',
    'deserted:adj = abandoned, uninhabited',
    'congested:adj = stuffed, overcrowded',
    'overseas:adj = abroad, foreign',
    'outside:adj = external, outer',
    'internal:adj = inner, interior',
    'adjacent:adj = neighbouring, adjoining',
    'urban:adj = city, metropolitan',
    'rural:adj = country, pastoral',
    'densely-populated:adj = crowded, teeming',
    'spacious:adj = roomy, capacious',
    'vacant:adj = empty, unoccupied',
    'accessible:adj = reachable, within reach',
    'inhospitable:adj = harsh, unwelcoming',
    'arid:adj = dry, parched',
    'fertile:adj = productive, rich',
    'earth:n = soil, ground',
    'surroundings:n = environment, setting',
    'habitat:n = home ground, natural home',
    'terrain:n = ground, landscape',
    'boundary:n = border, perimeter',
    'outskirts:n = fringes, edge',
    'vicinity:n = neighbourhood, surrounding area',
    'hole:n = gap, cavity',
    'route:n = way, itinerary',
    'destination:n = end point, goal',
    'dwelling:n = residence, home',
    'shelter:n = refuge, cover',
    'refuge:n = sanctuary, haven',
    'arrive:v = reach, get to',
    'approach:v = near, draw close to',
    'depart:v = leave, set off',
    'traverse:v = cross, travel over',
    'relocate:v = move, resettle',
    'disperse:v = scatter, spread out',
    'converge:v = meet, come together',
    'ascend:v = climb, go up',
    'descend:v = go down, drop',
    'circulate:v = move around, flow',
    'transport:v = carry, convey',
    'evacuate:v = clear, vacate',
    'inhabit:v = live in, occupy',
    'occupy:v = take up, inhabit',
    'settle:v = colonise, take up residence',
    'excavate:v = dig out, unearth',
    'erect:v = build, put up',
    'demolish:v = knock down, raze',
    'movie:n = film, picture',
    'midway:adv = halfway, in between',
    'nearby:adv = close at hand, not far',
    'abroad:adv = overseas, in another country',
    'elsewhere:adv = somewhere else, in another place',
    'downstream:adv = with the current, lower down',
    'landmark:n = feature, monument',
    'monument:n = memorial, landmark',
    'metropolis:n = city, capital',
    'suburb:n = outlying district, residential area',
    'province:n = region, territory',
    'territory:n = area, domain',
    'frontier:n = border, boundary',
    'passage:n = route, corridor',
    'corridor:n = passage, hallway',
  ],
};
