import { type IRawVocabularyGroup } from './schema';

/**
 * Rising, falling, becoming something else.
 *
 * Task 1 is a chart and the chart is a change, so this file is the one a
 * candidate uses under the most time pressure. `increase` five times in a
 * hundred and fifty words is the single commonest lexical failure in Academic
 * Writing, and every alternative to it is here.
 */
export const VOCAB_CHANGE: IRawVocabularyGroup = {
  topic: 'change',
  entries: [
    'minimize:v = play down, reduce',
    'magnify:v = expand, enlarge',
    'diminish:v = curtail, lessen',
    'elevate:v = raise, promote',
    'overhaul:v = overtake, revamp',
    'denationalize:v = privatize, sell off',
    'decontrol:v = deregulate, free up',
    'domesticate:v = cultivate, tame',
    'renounce:v = give up, forsake',
    'abandon:v = forsake, desert',
    'convalesce:v = recover, recuperate',
    'survive:v = outlive, endure',
    'thrive:v = prosper, flourish',
    'yield:v = produce, generate',
    'migrate:v = emigrate, relocate',
    'arise:v = occur, emerge',
    'begin:v = start, commence',
    'disappear:v = vanish, evaporate',
    'reintroduce:v = bring back, restore',
    'mend:v = repair, fix',
    'restore:v = reinstate, renew',
    'deteriorate:v = worsen, decline',
    'escalate:v = intensify, mount',
    'plummet:v = plunge, nosedive',
    'soar:v = climb, rocket',
    'fluctuate:v = vary, oscillate',
    'stabilise:v = level off, steady',
    'accelerate:v = speed up, hasten',
    'decelerate:v = slow down, ease off',
    'surge:n = upsurge, rush',
    'decline:n = downturn, fall',
    'transition:n = shift, changeover',
    'reform:n = overhaul, restructuring',
    'revival:n = resurgence, renewal',
    'upheaval:n = disruption, turmoil',
    'inflow:n = influx, inpouring',
    'surplus:n = excess, overflow',
    'impasse:n = deadlock, stalemate',
    'transitory:adj = temporary, fleeting',
    'intermittent:adj = sporadic, irregular',
    'drastic:adj = extreme, radical',
    'momentous:adj = powerful, far-reaching',
    'stationary:adj = fixed, unmoving',
    'steady:adj = regular, consistent',
    'constant:adj = fixed, unchanging',
    'stable:adj = steady, secure',
    'obsolete:adj = out of date, outmoded',
    'modern:adj = contemporary, up to date',
    'new:adj = fresh, novel',
    'former:adj = previous, erstwhile',
    'previous:adj = preceding, prior',
    'spontaneous:adj = automatic, unplanned',
    'gradual:adj = incremental, steady',
    'abrupt:adj = sudden, unexpected',
    'irreversible:adj = permanent, irrevocable',
    'volatile:adj = unstable, unpredictable',
    'increasingly:adv = more and more, progressively',
    'formerly:adv = previously, once',
    'eventually:adv = ultimately, in the end',
    'gradually:adv = slowly, step by step',
    'hitherto:adv = until now, previously',
    'evolve:v = develop, progress',
    'adapt:v = adjust, acclimatise',
    'transform:v = convert, remake',
    'undermine:v = weaken, erode',
    'reinforce:v = strengthen, bolster',
  ],
};
