import { type IRawVocabularyGroup } from './schema';

/**
 * Disagreement, difficulty, and things going wrong.
 *
 * Half of Task 2 is a problem and what to do about it, and a candidate who
 * writes *problem* nine times has described nine different things with one
 * word. An *obstacle* is not a *predicament* is not a *setback*, and naming
 * which one it is is most of the argument.
 */
export const VOCAB_CONFLICT: IRawVocabularyGroup = {
  topic: 'conflict',
  entries: [
    'conflict:n = clash, dispute',
    'uprising:n = rebellion, revolt',
    'terror:n = terrorism, dread',
    'misfortune:n = mishap, adversity',
    'misery:n = distress, wretchedness',
    'impediment:n = obstacle, hindrance',
    'obstacle:n = barrier, hurdle',
    'setback:n = reverse, blow',
    'predicament:n = plight, tight spot',
    'plight:n = predicament, distress',
    'grievance:n = complaint, resentment',
    'dispute:n = quarrel, disagreement',
    'controversy:n = dispute, contention',
    'friction:n = tension, discord',
    'turmoil:n = unrest, chaos',
    'hazard:n = danger, peril',
    'peril:n = danger, jeopardy',
    'threat:n = menace, danger',
    'damage:n = harm, injury',
    'housebreaking:n = burglary, break-in',
    'penalty:n = punishment, sanction',
    'sanction:n = penalty, embargo',
    'unlawful:adj = illegal, illicit',
    'insurgency:n = rebellion, revolt',
    'hostility:n = animosity, enmity',
    'withstand:v = resist, endure',
    'resist:v = oppose, withstand',
    'oppose:v = resist, contest',
    'defeat:v = beat, overcome',
    'overcome:v = surmount, conquer',
    'hinder:v = obstruct, impede',
    'impede:v = hamper, hold back',
    'hamper:v = restrict, encumber',
    'confine:v = restrict, limit',
    'restrain:v = curb, hold back',
    'suppress:v = stifle, quash',
    'ban:v = forbid, prohibit',
    'prohibit:v = forbid, outlaw',
    'contaminate:v = defile, pollute',
    'pollute:v = contaminate, foul',
    'jeopardise:v = endanger, imperil',
    'endanger:v = imperil, put at risk',
    'aggravate:v = worsen, exacerbate',
    'exacerbate:v = aggravate, inflame',
    'provoke:v = incite, goad',
    'annoy:v = irritate, bother',
    'irritate:v = exasperate, vex',
    'upset:v = perturb, distress',
    'mourn:v = grieve, lament',
    'grieve:v = mourn, sorrow',
    'rue:v = regret, lament',
    'quake:v = tremble, shudder',
    'seize:v = grab, confiscate',
    'grab:v = snatch, seize',
    'deprived:adj = disadvantaged, underprivileged',
    'disadvantaged:adj = deprived, marginalised',
    'miserable:adj = depressing, wretched',
    'dismal:adj = dark, bleak',
    'unfortunate:adj = unlucky, hapless',
    'vulnerable:adj = exposed, defenceless',
    'precarious:adj = unstable, insecure',
    'adverse:adj = unfavourable, hostile',
    'detrimental:adj = harmful, damaging',
    'inevitable:adj = unavoidable, inescapable',
    'unrest:n = disorder, agitation',
  ],
};
