import { type IRawVocabularyGroup } from './schema';

/**
 * When, how often, and in what order.
 *
 * These are the words that hold an answer together. A Speaking Part 2 answer
 * that runs *and then… and then… and then* is not short of ideas; it is short
 * of the eight connectives in this file, and the examiner marks it as the
 * second thing rather than the first.
 */
export const VOCAB_TIME: IRawVocabularyGroup = {
  topic: 'time',
  entries: [
    'consecutive:adj = successive, back to back',
    'immediate:adj = instant, instantaneous',
    'everlasting:adj = eternal, perpetual',
    'perpetual:adj = continuous, unending',
    'temporary:adj = short-lived, provisional',
    'brief:adj = short, concise',
    'prolonged:adj = extended, protracted',
    'imminent:adj = impending, approaching',
    'subsequent:adj = following, ensuing',
    'preceding:adj = earlier, prior',
    'simultaneous:adj = concurrent, at the same time',
    'periodic:adj = recurrent, cyclical',
    'annual:adj = yearly, once a year',
    'daybreak:n = dawn, sunrise',
    'sunrise:n = dawn, first light',
    'noon:n = midday, twelve',
    'nightfall:n = dusk, twilight',
    'today:adv = nowadays, currently',
    'anyway:adv = besides, in any case',
    'moreover:adv = in addition, furthermore',
    'notwithstanding:adv = however, nevertheless',
    'nevertheless:adv = even so, all the same',
    'meanwhile:adv = in the meantime, at the same time',
    'thereafter:adv = afterwards, subsequently',
    'presently:adv = shortly, soon',
    'seldom:adv = rarely, infrequently',
    'occasionally:adv = now and then, sporadically',
    'invariably:adv = always, without exception',
    'promptly:adv = without delay, immediately',
    'belatedly:adv = late, behind schedule',
    'moment:n = occasion, instant',
    'era:n = age, epoch',
    'decade:n = ten years, ten-year period',
    'duration:n = length, span',
    'interval:n = gap, break',
    'deadline:n = cut-off, time limit',
    'precedence:n = priority, seniority',
    'priority:n = precedence, first claim',
    'delay:n = holdup, postponement',
    'outset:n = beginning, start',
    'onset:n = beginning, commencement',
    'aftermath:n = consequences, wake',
    'legacy:n = inheritance, heritage',
    'postpone:v = defer, put off',
    'defer:v = delay, hold over',
    'hurry:v = rush, hasten',
    'linger:v = dawdle, remain',
    'precede:v = come before, lead',
    'coincide:v = happen together, overlap',
    'endure:v = last, persist',
    'persist:v = continue, carry on',
    'commence:v = begin, initiate',
    'terminate:v = end, conclude',
    'resume:v = restart, take up again',
    'suspend:v = halt, put on hold',
    'expire:v = lapse, run out',
    'off-season:n = quiet season, low season',
    'well-timed:adj = timely, opportune',
    'untimely:adj = premature, ill-timed',
    'overdue:adj = late, outstanding',
    'contemporary:adj = present-day, current',
    'ancient:adj = age-old, antiquated',
    'chronological:adj = in order, sequential',
    'ultimately:adv = finally, in the end',
  ],
};
