import { type IRawVocabularyGroup } from './schema';

/**
 * Saying, writing, arguing, agreeing.
 *
 * Every one of these has a plain twin a candidate already owns — *say*, *tell*,
 * *ask* — and the swap is the cheapest band the vocabulary section sells. The
 * words that move a mark are the ones with a *manner* built in: `grumble` is
 * not `say`, it is `say` plus the reason the examiner remembers it.
 */
export const VOCAB_COMMUNICATION: IRawVocabularyGroup = {
  topic: 'communication',
  entries: [
    'convey:v = communicate, impart',
    'cite:v = quote, reference',
    'citation:n = quotation, reference',
    'narrate:v = relate, recount',
    'respond:v = reply, answer',
    'notify:v = inform, apprise',
    'enquire:v = investigate, ask',
    'consult:v = refer to, seek advice from',
    'disclaim:v = deny, renounce',
    'antagonize:v = provoke, alienate',
    'grouse:v = grumble, complain',
    'assure:v = guarantee, reassure',
    'nominate:v = appoint, designate',
    'adjourn:v = postpone, suspend',
    'disagree:v = differ, dissent',
    'conform:v = comply, adhere',
    'mimic:v = imitate, copy',
    'praise:n = compliment, commendation',
    'testament:n = testimony, proof',
    'narrative:n = story, account',
    'refrain:n = chorus, repeated line',
    'instructions:n = directions, guidelines',
    'convention:n = conference, assembly',
    'meeting:n = assembly, gathering',
    'charter:n = constitution, founding document',
    'invoice:n = bill, statement',
    'ballot:n = poll, vote',
    'bid:n = tender, offer',
    'word:n = synonym, term',
    'signal:n = sign, indication',
    'hint:n = trace, clue',
    'ornament:n = decoration, embellishment',
    'unstated:adj = unspoken, implicit',
    'knowingly:adv = deliberately, wittingly',
    'informal:adj = casual, colloquial',
    'transparent:adj = obvious, self-evident',
    'understandable:adj = comprehensible, intelligible',
    'deceptive:adj = misleading, deceitful',
    'insinuate:v = imply, hint',
    'articulate:v = express, put into words',
    'elaborate:v = expand on, develop',
    'summarise:v = condense, recap',
    'abbreviate:v = condense, shorten',
    'reiterate:v = repeat, restate',
    'emphasise:v = stress, underline',
    'persuade:v = convince, win over',
    'urge:v = press, exhort',
    'assert:v = declare, maintain',
    'allege:v = claim, contend',
    'confide:v = entrust, unburden',
    'divulge:v = reveal, disclose',
    'withhold:v = keep back, retain',
    'rebuke:v = reprimand, admonish',
    'commend:v = praise, applaud',
    'endorse:v = approve, back',
    'protest:v = object, demonstrate',
    'negotiate:v = bargain, mediate',
    'mediate:v = arbitrate, intervene',
    'jargon:n = terminology, cant',
    'anecdote:n = story, account',
    'rhetoric:n = oratory, persuasion',
    'discourse:n = discussion, debate',
    'correspondence:n = letters, communication',
    'terminology:n = vocabulary, nomenclature',
    'connotation:n = implication, overtone',
  ],
};
