import { type IRawVocabularyGroup } from './schema';

/**
 * Work, money, law and government — the four topics Reading is set on.
 *
 * A Reading passage does not define `deregulate` before it uses it, and the
 * question that turns on the word is usually a True/False/Not Given. This file
 * is therefore the one with the most direct effect on a Reading band: nothing
 * in it is hard to *say*, and every entry is a word a passage assumes.
 */
export const VOCAB_WORK: IRawVocabularyGroup = {
  topic: 'work',
  entries: [
    'oversee:v = supervise, superintend',
    'appoint:v = nominate, designate',
    'delegate:v = assign, entrust',
    'recruit:v = enlist, take on',
    'dismiss:v = sack, discharge',
    'resign:v = step down, quit',
    'retire:v = step down, withdraw',
    'privatize:v = sell off, denationalise',
    'deregulate:v = decontrol, liberalise',
    'subsidise:v = fund, support',
    'invest:v = put money into, back',
    'incur:v = run up, bring on',
    'allocate:v = assign, apportion',
    'distribute:v = hand out, disperse',
    'procure:v = obtain, acquire',
    'acquire:v = obtain, secure',
    'audit:v = inspect, examine',
    'inspect:v = examine, scrutinise',
    'implement:v = carry out, put into effect',
    'enforce:v = impose, apply',
    'regulate:v = govern, control',
    'exploit:v = take advantage of, utilise',
    'outsource:v = contract out, subcontract',
    'revenue:n = income, takings',
    'expenditure:n = spending, outlay',
    'profit:n = gain, return',
    'debt:n = liability, arrears',
    'wage:n = pay, earnings',
    'salary:n = pay, remuneration',
    'incentive:n = inducement, motivation',
    'subsidy:n = grant, financial support',
    'stakeholder:n = interested party, participant',
    'commerce:n = trade, business',
    'enterprise:n = venture, undertaking',
    'monopoly:n = sole control, exclusive hold',
    'recession:n = downturn, slump',
    'infrastructure:n = framework, facilities',
    'legislation:n = law, statute',
    'statute:n = law, act',
    'jurisdiction:n = authority, remit',
    'mandate:n = authority, directive',
    'bureaucracy:n = officialdom, red tape',
    'constitution:n = structure, charter',
    'association:n = organisation, body',
    'branch:n = department, division',
    'inheritor:n = heir, beneficiary',
    'business:n = trade, commerce',
    'paper money:n = notes, currency',
    'pocket book:n = notebook, wallet',
    'workforce:n = staff, personnel',
    'colleague:n = co-worker, associate',
    'vacancy:n = opening, unfilled post',
    'occupation:n = job, profession',
    'vocation:n = calling, profession',
    'productivity:n = output, efficiency',
    'lucrative:adj = profitable, well-paid',
    'affluent:adj = wealthy, prosperous',
    'prosperous:adj = successful, thriving',
    'successful:adj = accomplished, effective',
    'mandatory:adj = compulsory, obligatory',
    'voluntary:adj = optional, unpaid',
    'eligible:adj = qualified, entitled',
    'liable:adj = responsible, answerable',
    'corporate:adj = business, company-wide',
  ],
};
