import { type IRawVocabularyGroup } from './schema';

/**
 * What a person is like — the adjectives an examiner hears most, and the ones
 * that would have earned the band.
 *
 * The heaviest file in the corpus, and deliberately so. Speaking Part 2 is
 * overwhelmingly *describe a person*, and the words a candidate reaches for
 * there — nice, bad, clever, lazy — are the four that cost the most marks.
 */
export const VOCAB_CHARACTER: IRawVocabularyGroup = {
  topic: 'character',
  entries: [
    'negligent:adj = inattentive, careless',
    'eccentric:adj = unusual, unconventional',
    'morose:adj = sullen, gloomy',
    'arrogant:adj = haughty, conceited',
    'immodest:adj = conceited, boastful',
    'blameless:adj = innocent, guiltless',
    'artful:adj = crafty, cunning',
    'foxy:adj = cunning, sly',
    'naughty:adj = disobedient, mischievous',
    'depraved:adj = wicked, corrupt',
    'crook:n = criminal, offender',
    'insurgent:n = rebel, insurrectionist',
    'immature:adj = inexperienced, childish',
    'conscious:adj = aware, mindful',
    'egocentric:adj = selfish, self-centred',
    'hospitable:adj = cordial, welcoming',
    'dedicated:adj = committed, devoted',
    'ignorant:adj = unaware, uninformed',
    'intolerant:adj = bigoted, narrow-minded',
    'illiberal:adj = intolerant, prejudiced',
    'touchy:adj = sensitive, irritable',
    'cranky:adj = cross, irritable',
    'loopy:adj = crazy, eccentric',
    'crazy:adj = insane, deranged',
    'honest:adj = truthful, sincere',
    'sincere:adj = honest, genuine',
    'mean:adj = unkind, ungenerous',
    'hostile:adj = antagonistic, unfriendly',
    'aggressive:adj = militant, forceful',
    'militant:adj = combative, aggressive',
    'impetuous:adj = reckless, impulsive',
    'obdurate:adj = stubborn, unyielding',
    'cussed:adj = stubborn, contrary',
    'docile:adj = tame, compliant',
    'impassive:adj = emotionless, unmoved',
    'detached:adj = indifferent, dispassionate',
    'impartial:adj = neutral, unbiased',
    'unbiased:adj = impartial, even-handed',
    'trustworthy:adj = reliable, dependable',
    'moral:adj = ethical, principled',
    'nobility:n = aristocracy, gentry',
    'repute:n = reputation, standing',
    'remorse:n = regret, contrition',
    'mendacity:n = lying, dishonesty',
    'fanatic:n = enthusiast, zealot',
    'confederate:n = accomplice, associate',
    'middleman:n = intermediary, go-between',
    'clerk:n = receptionist, official',
    'amateur:n = beginner, novice',
    'native:n = local, inhabitant',
    'migrant:n = drifter, nomad',
    'magician:n = conjuror, illusionist',
    'infamous:adj = notorious, disreputable',
    'noted:adj = famous, celebrated',
    'famous:adj = renowned, celebrated',
    'highbrow:adj = intellectual, cultured',
    'stupid:adj = dense, slow-witted',
    'foolish:adj = silly, unwise',
    'fool:n = idiot, simpleton',
    'awkward:adj = clumsy, ungainly',
    'self-assured:adj = confident, poised',
    'choosy:adj = picky, selective',
    'conservative:adj = cautious, traditional',
    'independent:adj = autonomous, self-reliant',
    'jealous:adj = envious, covetous',
    'insolvent:adj = bankrupt, ruined',
    'disgrace:n = shame, dishonour',
    'gratuity:n = tip, bonus',
  ],
};
