import { type IRawVocabularyGroup } from './schema';

/**
 * How much, how many, how far.
 *
 * The other half of Task 1, and the half candidates get wrong more quietly:
 * `a lot of` is not a band error the way `increase` repeated is, it is simply
 * the word an eleven-year-old would use. Nothing here is difficult; all of it
 * is the register the task expects.
 */
export const VOCAB_QUANTITY: IRawVocabularyGroup = {
  topic: 'quantity',
  entries: [
    'vast:adj = huge, immense',
    'huge:adj = enormous, colossal',
    'enormous:adj = immense, massive',
    'abundant:adj = ample, plentiful',
    'appreciable:adj = considerable, substantial',
    'scarcity:n = shortage, dearth',
    'scarce:adj = sparse, in short supply',
    'infrequent:adj = rare, occasional',
    'moderately:adv = reasonably, fairly',
    'practically:adv = virtually, almost',
    'completely:adv = totally, entirely',
    'chiefly:adv = mainly, primarily',
    'immoderate:adj = excessive, extravagant',
    'excessive:adj = inordinate, disproportionate',
    'nugatory:adj = worthless, trifling',
    'trivial:adj = worthless, insignificant',
    'valueless:adj = worthless, useless',
    'vain:adj = useless, futile',
    'measure:n = degree, extent',
    'extent:n = scope, magnitude',
    'inventory:n = stock, holdings',
    'discount:n = reduction, markdown',
    'proportion:n = share, ratio',
    'fraction:n = portion, part',
    'majority:n = bulk, greater part',
    'minority:n = smaller part, remainder',
    'threshold:n = limit, starting point',
    'ceiling:n = upper limit, cap',
    'aggregate:n = total, sum',
    'sum:n = total, amount',
    'peak:n = zenith, high point',
    'zenith:n = peak, summit',
    'trough:n = low point, dip',
    'margin:n = difference, gap',
    'ratio:n = proportion, balance',
    'bulk:n = mass, majority',
    'accumulate:v = amass, build up',
    'exceed:v = surpass, outstrip',
    'outnumber:v = exceed, overwhelm',
    'double:v = duplicate, multiply',
    'halve:v = reduce by half, split',
    'divide:v = split, separate',
    'deplete:v = exhaust, drain',
    'empty:v = drain, evacuate',
    'ample:adj = sufficient, generous',
    'sufficient:adj = adequate, enough',
    'negligible:adj = insignificant, minimal',
    'marginal:adj = slight, minor',
    'substantial:adj = considerable, sizeable',
    'considerable:adj = significant, notable',
    'sizeable:adj = large, substantial',
    'minute:adj = tiny, microscopic',
    'high:adj = elevated, lofty',
    'extra:adj = additional, supplementary',
    'additional:adj = further, supplementary',
    'numerous:adj = many, countless',
    'countless:adj = innumerable, myriad',
    'finite:adj = limited, bounded',
    'infinite:adj = boundless, limitless',
    'roughly:adv = approximately, about',
    'approximately:adv = roughly, around',
    'barely:adv = scarcely, hardly',
    'considerably:adv = significantly, markedly',
    'slightly:adv = marginally, a little',
    'predominantly:adv = mostly, largely',
  ],
};
