import { type IRawVocabularyGroup } from './schema';

/**
 * Good, bad, and everything a candidate says *very* in front of.
 *
 * `very good` and `very bad` are the two phrases the Speaking band descriptors
 * are quietly built to catch: an intensifier is what somebody reaches for when
 * they do not have the word. `superb` and `dreadful` need no `very`, and that
 * is the whole lesson of this file.
 */
export const VOCAB_QUALITY: IRawVocabularyGroup = {
  topic: 'quality',
  entries: [
    'inferior:adj = substandard, second-rate',
    'superb:adj = magnificent, outstanding',
    'lousy:adj = awful, dreadful',
    'dreadful:adj = terrible, appalling',
    'awful:adj = atrocious, terrible',
    'imperfect:adj = faulty, flawed',
    'immaculate:adj = spotless, flawless',
    'scrumptious:adj = delicious, delectable',
    'revolting:adj = disgusting, repugnant',
    'cheesy:adj = corny, tacky',
    'drab:adj = dull, colourless',
    'monotonous:adj = boring, repetitive',
    'insupportable:adj = intolerable, unbearable',
    'insufferable:adj = unbearable, intolerable',
    'disagreeable:adj = unpleasant, distasteful',
    'attractive:adj = appealing, alluring',
    'beneficial:adj = favourable, advantageous',
    'economic:adj = profitable, cost-effective',
    'legitimate:adj = valid, lawful',
    'applicable:adj = relevant, pertinent',
    'essential:adj = fundamental, indispensable',
    'imperative:adj = vital, crucial',
    'special:adj = exceptional, distinctive',
    'exceptional:adj = outstanding, extraordinary',
    'convenient:adj = handy, accessible',
    'cozy:adj = comfortable, snug',
    'lethal:adj = deadly, fatal',
    'poisonous:adj = toxic, venomous',
    'curative:adj = healing, therapeutic',
    'beneficent:adj = generous, benevolent',
    'nameless:adj = anonymous, unnamed',
    'organic:adj = biological, natural',
    'manmade:adj = artificial, synthetic',
    'uncooked:adj = raw, unprepared',
    'dry:adj = arid, parched',
    'bendy:adj = flexible, pliable',
    'hard:adj = firm, rigid',
    'torpid:adj = lethargic, sluggish',
    'prompt:adj = immediate, punctual',
    'dicey:adj = risky, precarious',
    'robust:adj = sturdy, resilient',
    'fragile:adj = delicate, brittle',
    'coarse:adj = rough, unrefined',
    'sophisticated:adj = refined, advanced',
    'crude:adj = rudimentary, unrefined',
    'authentic:adj = genuine, bona fide',
    'counterfeit:adj = fake, forged',
    'redundant:adj = superfluous, unnecessary',
    'versatile:adj = adaptable, all-round',
    'sustainable:adj = viable, enduring',
    'viable:adj = feasible, workable',
    'feasible:adj = practicable, achievable',
    'notorious:adj = infamous, disreputable',
    'comfort:n = consolation, solace',
    'mirth:n = fun, merriment',
    'fragrance:n = perfume, scent',
    'ardor:n = passion, fervour',
    'constancy:n = fidelity, steadfastness',
    'equity:n = fairness, impartiality',
    'nuisance:n = annoyance, irritation',
    'flaw:n = defect, blemish',
    'merit:n = worth, virtue',
    'asset:n = advantage, resource',
    'drawback:n = disadvantage, downside',
  ],
};
