import { type IRawVocabularyGroup } from './schema';

/**
 * Thinking, judging, believing — the verbs and nouns of Writing Task 2.
 *
 * An essay is a sequence of claims about what somebody believes, infers,
 * concedes and concludes. A candidate with one word for all of it writes *I
 * think* eleven times, and the band descriptor for lexical resource is
 * describing exactly that paragraph.
 */
export const VOCAB_THOUGHT: IRawVocabularyGroup = {
  topic: 'thought',
  entries: [
    'deduce:v = infer, conclude',
    'perception:n = insight, awareness',
    'hypothesis:n = speculation, theory',
    'precept:n = principle, doctrine',
    'assume:v = suppose, presume',
    'presume:v = assume, take for granted',
    'contemplate:v = consider, ponder',
    'ponder:v = reflect, deliberate',
    'discern:v = distinguish, perceive',
    'differentiate:v = distinguish, tell apart',
    'misconceive:v = misunderstand, misjudge',
    'misread:v = misinterpret, misconstrue',
    'doubt:n = mistrust, scepticism',
    'vague:adj = indistinct, imprecise',
    'apparent:adj = evident, obvious',
    'indisputable:adj = undeniable, incontestable',
    'accurate:adj = correct, precise',
    'satisfied:adj = convinced, content',
    'plausible:adj = credible, believable',
    'rational:adj = logical, reasoned',
    'arbitrary:adj = random, capricious',
    'ambiguous:adj = unclear, equivocal',
    'coherent:adj = consistent, logical',
    'profound:adj = deep, far-reaching',
    'shrewd:adj = astute, perceptive',
    'astute:adj = shrewd, discerning',
    'intuitive:adj = instinctive, innate',
    'sceptical:adj = doubtful, unconvinced',
    'dogmatic:adj = opinionated, inflexible',
    'objective:adj = detached, factual',
    'subjective:adj = personal, biased',
    'abstract:n = summary, synopsis',
    'precis:n = summary, abridgement',
    'construction:n = interpretation, reading',
    'notion:n = idea, concept',
    'insight:n = understanding, discernment',
    'rationale:n = reasoning, justification',
    'premise:n = assumption, proposition',
    'inference:n = deduction, conclusion',
    'consensus:n = agreement, accord',
    'paradox:n = contradiction, absurdity',
    'dilemma:n = quandary, predicament',
    'criterion:n = standard, benchmark',
    'bias:n = prejudice, partiality',
    'scrutiny:n = examination, inspection',
    'speculate:v = conjecture, theorise',
    'ascertain:v = determine, establish',
    'perceive:v = notice, discern',
    'recall:v = remember, recollect',
    'anticipate:v = expect, foresee',
    'foresee:v = predict, anticipate',
    'overlook:v = miss, disregard',
    'disregard:v = ignore, dismiss',
    'concede:v = admit, acknowledge',
    'acknowledge:v = admit, recognise',
    'advocate:v = support, champion',
    'refute:v = disprove, rebut',
    'justify:v = defend, vindicate',
    'imply:v = suggest, insinuate',
    'infer:v = deduce, gather',
    'clarify:v = explain, elucidate',
    'illustrate:v = demonstrate, exemplify',
    'denote:v = indicate, signify',
    'symbolize:v = represent, stand for',
    'visualize:v = imagine, picture',
    'phantasm:n = illusion, apparition',
  ],
};
