import { type IRawVocabularyGroup } from './schema';

/**
 * The plain word, and the one that reads as English rather than as translation.
 *
 * This file is the corpus at its most literal: every headword is a word a
 * candidate already has, and every synonym is what a first-language speaker
 * would have written instead. Nothing here teaches a new idea — it swaps a word
 * for the same word at a different height, which is precisely what the lexical
 * resource descriptor is measuring.
 */
export const VOCAB_EVERYDAY: IRawVocabularyGroup = {
  topic: 'everyday',
  entries: [
    'win:v = succeed, prevail',
    'hold:v = grasp, grip',
    'near:v = approach, close in on',
    'impact:v = affect, influence',
    'affect:v = bear on, influence',
    'cope:v = manage, get by',
    'achieve:v = accomplish, attain',
    'attain:v = achieve, reach',
    'operate:v = function, run',
    'function:v = operate, work',
    'collect:v = gather, amass',
    'receive:v = get, obtain',
    'confuse:v = mix up, bewilder',
    'appear:v = seem, look',
    'intend:v = mean, plan',
    'continue:v = persist, carry on',
    'vary:v = differ, fluctuate',
    'beat:v = defeat, outdo',
    'bring up:v = raise, rear',
    'hand out:v = distribute, give out',
    'put back:v = postpone, reschedule',
    'play down:v = minimise, understate',
    'give up:v = renounce, abandon',
    'take on:v = undertake, assume',
    'carry out:v = perform, execute',
    'point out:v = indicate, note',
    'set up:v = establish, found',
    'look into:v = investigate, examine',
    'find out:v = discover, ascertain',
    'work out:v = calculate, resolve',
    'easy:adj = simple, effortless',
    'difficult:adj = hard, demanding',
    'worn:adj = old, threadbare',
    'uncommon:adj = unusual, rare',
    'unusual:adj = strange, out of the ordinary',
    'pressing:adj = urgent, critical',
    'urgent:adj = pressing, immediate',
    'particular:adj = specific, individual',
    'contrary:adj = opposite, conflicting',
    'dirty:adj = soiled, grimy',
    'missing:adj = lost, absent',
    'away:adj = absent, out',
    'fortunate:adj = lucky, blessed',
    'leading:adj = main, foremost',
    'wrong:adj = mistaken, erroneous',
    'lacking:adj = missing, deficient',
    'naked:adj = bare, uncovered',
    'mild:adj = gentle, moderate',
    'uninjured:adj = unhurt, unscathed',
    'unmarried:adj = single, unattached',
    'uncared for:adj = neglected, untended',
    'rude:adj = impolite, discourteous',
    'mysterious:adj = occult, enigmatic',
    'help:n = aid, assistance',
    'ability:n = skill, capacity',
    'selection:n = choice, range',
    'enemy:n = opponent, adversary',
    'opportunity:n = possibility, opening',
    'possibility:n = opportunity, prospect',
    'cube:n = dice, block',
    'occasion:n = event, moment',
    'aid:v = help, assist',
    'maybe:adv = perhaps, possibly',
    'happily:adv = fortunately, luckily',
    'anyhow:adv = in any case, regardless',
  ],
};
