import { type IRawVocabularyGroup } from './schema';

/**
 * Health, the body, and the senses.
 *
 * Health is the single most set Task 2 topic after education, and it is the one
 * where a candidate is most likely to have the idea and not the word: everybody
 * can argue about hospitals, and *immune*, *chronic* and *contagious* are what
 * separate the argument that scores from the one that gestures.
 */
export const VOCAB_BODY: IRawVocabularyGroup = {
  topic: 'body',
  entries: [
    'immune:adj = exempt, resistant',
    'lethargic:adj = sluggish, listless',
    'chronic:adj = persistent, long-standing',
    'acute:adj = severe, sharp',
    'contagious:adj = infectious, catching',
    'benign:adj = harmless, non-threatening',
    'nutritious:adj = nourishing, wholesome',
    'obese:adj = overweight, corpulent',
    'sedentary:adj = inactive, desk-bound',
    'strenuous:adj = demanding, taxing',
    'fatigued:adj = exhausted, worn out',
    'dead:adj = lifeless, deceased',
    'gut:n = intestine, bowel',
    'forehead:n = brow, temple',
    'coiffure:n = hairstyle, hairdo',
    'mannequin:n = model, dummy',
    'denims:n = jeans, dungarees',
    'mackintosh:n = waterproof coat, raincoat',
    'napkin:n = serviette, table linen',
    'garbage can:n = trashcan, dustbin',
    'couch:n = sofa, settee',
    'gravestone:n = headstone, memorial',
    'post-mortem:n = autopsy, examination after death',
    'hunger:n = starvation, famine',
    'famine:n = starvation, food shortage',
    'diet:n = regimen, eating pattern',
    'remedy:n = cure, treatment',
    'symptom:n = sign, indication',
    'ailment:n = illness, complaint',
    'epidemic:n = outbreak, plague',
    'longevity:n = long life, life expectancy',
    'hygiene:n = cleanliness, sanitation',
    'sanitation:n = drainage, public hygiene',
    'nutrition:n = nourishment, sustenance',
    'therapy:n = treatment, rehabilitation',
    'heal:v = cure, mend',
    'recover:v = recuperate, get better',
    'alleviate:v = relieve, ease',
    'relieve:v = ease, soothe',
    'diagnose:v = identify, determine',
    'inoculate:v = vaccinate, immunise',
    'exhaust:v = tire out, drain',
    'ingest:v = swallow, consume',
    'consume:v = eat, use up',
    'candy:n = sweet, confectionery',
    'food:n = nourishment, provisions',
    'sight:n = vision, eyesight',
    'audible:adj = hearable, discernible',
    'visible:adj = perceptible, in view',
    'tangible:adj = touchable, concrete',
    'pungent:adj = sharp, acrid',
    'bland:adj = tasteless, insipid',
    'delicious:adj = tasty, mouth-watering',
    'fragrant:adj = sweet-smelling, aromatic',
    'deafening:adj = ear-splitting, thunderous',
    'faint:adj = weak, indistinct',
    'numb:adj = unfeeling, deadened',
    'weary:adj = tired, drained',
    'vigour:n = energy, vitality',
    'stamina:n = endurance, staying power',
    'posture:n = bearing, stance',
    'infirm:adj = frail, feeble',
    'frail:adj = weak, delicate',
  ],
};
