import { z } from 'zod';

/**
 * The thousand English verbs, in all five forms.
 *
 * **Where this comes from.** `1000 most common English Verbs and tense forms`,
 * the reference list the user supplied, read row by row rather than recalled.
 * Two rows are not in it as written: row 48 is laid out as `be (am,are)` and
 * does not parse as a five-column row, so `be` is restored by hand from that
 * same row; row 856 is blank in the source. One row is corrected — the source
 * prints `entangling` in `endanger`'s `-ing` column, which is a typesetting
 * slip rather than an irregular form. `forlese` is dropped: it is archaic and
 * its own s-form column repeats the base word. Nothing else is added, removed
 * or improved.
 *
 * **Why a regular verb is stored as one word.** `accept` is written `accept`,
 * not `accept accepted accepted accepts accepting`, because the other four
 * forms are *generated by rule* — and the rule is the thing worth teaching. A
 * corpus that spelled all five out would be five times the size and would say
 * nothing about why `stop` doubles its p and `hope` drops its e. 764 of these
 * 998 verbs are one word here.
 *
 * The rules live in `VerbConjugator` in the domain, not in this directory, and
 * `content:validate` runs the corpus through them: an `ing=` or `s=` override
 * that the rules would have produced anyway fails the build, so an exception
 * cannot quietly accumulate where a rule already worked. That check is what
 * makes "derived" true rather than merely intended — it caught the corpus down
 * to 35 real exceptions out of 998, and every one of them is a stressed final
 * syllable (`admit`), a British doubled l (`travel`), or a verb that is simply
 * a law unto itself (`be`, `have`).
 *
 * **Why the Bangla is partial.** 116 of the 998 carry a Bangla gloss and the
 * rest do not. Those are the verbs a learner meets in the first week, where a
 * one-word gloss is safe: `eat` is খাওয়া and there is nothing to argue about.
 * Writing 998 of them would mean writing several hundred that need a phrase, a
 * register note or a context to be true, and a wrong gloss on a screen whose
 * whole subject is being right about English costs more than a blank cell. The
 * `words` table's 3,000 checked glosses are the place for the rest, and the
 * `course` badge is the bridge.
 */

/** At least one Bangla codepoint — the Bengali block is U+0980..U+09FF. */
const BANGLA_SCRIPT = /[ঀ-৿]/u;

/**
 * A verb form as written: lower case letters, and a slash where English
 * genuinely offers two — `was/were`, `chid/chidden`, `fit/fitted`. The slash is
 * kept rather than resolved because picking one would be inventing a preference
 * the source does not state, and both forms are what a learner will meet.
 */
const FORM = /^[a-z]+(?:-[a-z]+)*(?:\/[a-z]+(?:-[a-z]+)*)*$/u;

export const VERB_RANGES = ['a-d', 'e-l', 'm-r', 's-z'] as const;

export type VerbRange = (typeof VERB_RANGES)[number];

export interface IVerbEntry {
  /** V1 — the dictionary form. */
  readonly base: string;
  /** V2, or null when the verb is regular and the past is derived. */
  readonly past: string | null;
  /** V3, or null for the same reason. */
  readonly participle: string | null;
  /** V4, only where the -ing rule does not reach it. */
  readonly presentParticiple: string | null;
  /** V5, only where the -s rule does not reach it. */
  readonly thirdPerson: string | null;
  /**
   * Which verb this is, when the spelling is two verbs.
   *
   * `lie` is two words that happen to be spelled alike: one reclines and takes
   * `lay / lain`, the other tells an untruth and takes `lied / lied`. The source
   * list carries both rows and so does this corpus — a screen that showed one
   * would be teaching that the other is wrong. Null for the 990 verbs where the
   * spelling means one thing.
   */
  readonly sense: string | null;
  /** One of the hundred a learner is pointed at first. */
  readonly isCore: boolean;
  readonly banglaMeaning: string | null;
}

/** One content file. */
export interface IRawVerbGroup {
  readonly range: VerbRange;
  readonly entries: readonly string[];
}

export const rawVerbGroupSchema = z.object({
  range: z.enum(VERB_RANGES),
  entries: z.array(z.string().min(1)).min(1),
});

export interface IParseFailure {
  readonly path: string;
  readonly message: string;
}

/**
 * Parses one line into an entry, or reports why it cannot be.
 *
 * The checks that matter are the ones a careless edit slips past: a past form
 * given without a participle (which would render a three-column row with one
 * column blank), a malformed override, and a Bangla gloss typed in
 * transliteration rather than in Bangla script. None of these throw —
 * the caller collects every issue so one run names them all.
 */
export function parseVerbEntry(line: string): {
  readonly entry: IVerbEntry | null;
  readonly issues: readonly IParseFailure[];
} {
  const trimmed = line.trim();
  const isCore = trimmed.startsWith('*');
  /*
   * Split at the first `key=` token rather than matching the whole line with
   * one expression. A Bangla gloss is a phrase — `বহন করা` has a space in it —
   * and a single regex that allowed spaces inside a value while still ending at
   * the next key was the least readable line in this directory. Two small
   * splits say the same thing and can be read.
   */
  const parts = (isCore ? trimmed.slice(1) : trimmed).split(/\s+(?=(?:ing|s|bn|sense)=)/u);
  const forms = (parts[0] ?? '').trim().split(/\s+/u);
  const issues: IParseFailure[] = [];
  const overrides = new Map<string, string>();

  for (const token of parts.slice(1)) {
    const at = token.indexOf('=');
    const key = token.slice(0, at);
    const value = token.slice(at + 1).trim();

    if (overrides.has(key)) {
      issues.push({ path: forms[0] ?? line, message: `"${key}=" is given twice` });
      continue;
    }

    overrides.set(key, value);
  }

  const [base = '', past, participle] = forms;

  if (base === '' || !/^[a-z]+(?:-[a-z]+)*$/u.test(base)) {
    return { entry: null, issues: [{ path: line, message: 'does not begin with a base form' }] };
  }

  if (forms.length !== 1 && forms.length !== 3) {
    issues.push({
      path: base,
      message: 'write a verb as its base alone, or as base, past and participle',
    });
  }

  for (const [key, value] of overrides) {
    if (key === 'sense') {
      continue;
    }

    if (key === 'bn') {
      if (!BANGLA_SCRIPT.test(value)) {
        issues.push({ path: base, message: 'bn must be Bangla script, not transliterated' });
      }
      continue;
    }

    if (!FORM.test(value)) {
      issues.push({ path: base, message: `"${value}" is not a verb form` });
    }
  }

  for (const form of [past, participle]) {
    if (form !== undefined && !FORM.test(form)) {
      issues.push({ path: base, message: `"${form}" is not a verb form` });
    }
  }

  if (issues.length > 0) {
    return { entry: null, issues };
  }

  return {
    entry: {
      base,
      past: past ?? null,
      participle: participle ?? null,
      presentParticiple: overrides.get('ing') ?? null,
      thirdPerson: overrides.get('s') ?? null,
      sense: overrides.get('sense') ?? null,
      isCore,
      banglaMeaning: overrides.get('bn') ?? null,
    },
    issues: [],
  };
}
