import { type IRawVerbGroup } from './schema';

/**
 * E to L.
 *
 * Written the way `schema.ts` describes: a regular verb is **one word**,
 * because its other four forms are derived rather than stored. Three words
 * means the past and the participle are irregular; an `ing=` or `s=` token
 * means the spelling rule does not reach that form and the exception is
 * recorded rather than guessed at. A leading `*` marks one of the hundred a
 * learner meets first.
 */
export const VERBS_E_L: IRawVerbGroup = {
  range: 'e-l',
  entries: [
    "earn",
    "*eat ate eaten bn=খাওয়া",
    "educate",
    "empower",
    "empty",
    "encircle",
    "encourage",
    "encroach",
    "endanger",
    "endorse",
    "endure",
    "engrave",
    "enjoy",
    "enlarge",
    "enlighten",
    "enter",
    "envy",
    "erase",
    "escape",
    "evaporate",
    "exchange",
    "exclaim",
    "exclude",
    "exist",
    "expand",
    "expect",
    "explain bn=ব্যাখ্যা করা",
    "explore",
    "express",
    "extend",
    "eye",
    "face",
    "fail",
    "faint",
    "*fall fell fallen bn=পড়ে যাওয়া",
    "fan",
    "fancy",
    "favour",
    "fax",
    "feed fed fed",
    "*feel felt felt bn=অনুভব করা",
    "ferry",
    "fetch",
    "fight fought fought",
    "fill",
    "*find found found bn=খুঁজে পাওয়া",
    "finish bn=শেষ করা",
    "fish",
    "fit fit/fitted fit/fitted",
    "fix",
    "fizz",
    "flap",
    "flash",
    "flee fled fled",
    "fling flung flung",
    "float",
    "flop",
    "*fly flew flown bn=ওড়া",
    "fold",
    "follow bn=অনুসরণ করা",
    "forbid forbade forbidden ing=forbidding",
    "force",
    "forecast forecast forecast",
    "foretell foretold foretold",
    "*forget forgot forgotten ing=forgetting bn=ভুলে যাওয়া",
    "forgive forgave forgiven",
    "form",
    "forsake forsook forsaken",
    "found",
    "frame",
    "free",
    "freeze froze frozen",
    "frighten",
    "fry",
    "fulfil fulfilled fulfilled ing=fulfilling",
    "gag",
    "gain",
    "gainsay gainsaid gainsaid",
    "gash",
    "gaze",
    "*get got got bn=পাওয়া",
    "*give gave given bn=দেওয়া",
    "glance",
    "glitter",
    "glow",
    "*go went gone bn=যাওয়া",
    "google",
    "govern",
    "grab",
    "grade",
    "grant",
    "greet",
    "grind ground ground",
    "grip",
    "*grow grew grown bn=বেড়ে ওঠা",
    "guard",
    "guess",
    "guide",
    "handle",
    "hang hung hung",
    "happen bn=ঘটা",
    "harm",
    "hatch",
    "hate",
    "*have had had s=has bn=থাকা",
    "heal",
    "*hear heard heard bn=শোনা",
    "heave hove hove",
    "*help bn=সাহায্য করা",
    "hew hewed hewn",
    "hide hid hidden",
    "hinder",
    "hiss",
    "hit hit hit",
    "hoax",
    "*hold held held bn=ধরে রাখা",
    "hop",
    "hope",
    "horrify",
    "hug",
    "hum",
    "humiliate",
    "hunt",
    "hurl",
    "hurry",
    "*hurt hurt hurt bn=আঘাত করা",
    "hush",
    "hustle",
    "hypnotize",
    "idealize",
    "identify",
    "idolize",
    "ignite",
    "ignore",
    "ill-treat",
    "illuminate",
    "illumine",
    "illustrate",
    "imagine",
    "imbibe",
    "imitate",
    "immerse",
    "immolate",
    "immure",
    "impair",
    "impart",
    "impeach",
    "impede",
    "impel impelled impelled ing=impelling",
    "impend",
    "imperil imperilled imperilled ing=imperilling",
    "impinge",
    "implant",
    "implicate",
    "implode",
    "implore",
    "imply",
    "import",
    "impose",
    "impress",
    "imprint",
    "imprison",
    "improve",
    "inaugurate",
    "incise",
    "include",
    "increase",
    "inculcate",
    "indent",
    "indicate",
    "induce",
    "indulge",
    "infect",
    "infest",
    "inflame",
    "inflate",
    "inflect",
    "inform",
    "infringe",
    "infuse",
    "ingest",
    "inhabit",
    "inhale",
    "inherit",
    "initiate",
    "inject",
    "injure",
    "inlay inlaid inlaid",
    "innovate",
    "input input input ing=inputting",
    "inquire",
    "inscribe",
    "insert",
    "inspect",
    "inspire",
    "install",
    "insult",
    "insure",
    "integrate",
    "introduce",
    "invent",
    "invite",
    "join",
    "jump bn=লাফানো",
    "justify",
    "*keep kept kept bn=রাখা",
    "kick",
    "kid",
    "kill",
    "kiss",
    "kneel knelt knelt",
    "knit knit knit",
    "knock",
    "*know knew known bn=জানা",
    "lade laded laden",
    "land",
    "last",
    "latch",
    "laugh bn=হাসা",
    "*lay laid laid",
    "*lead led led bn=নেতৃত্ব দেওয়া",
    "leak",
    "lean leant leant",
    "leap leapt leapt",
    "*learn learnt learnt bn=শেখা",
    "*leave left left bn=ছেড়ে যাওয়া",
    "leer",
    "*lend lent lent bn=ধার দেওয়া",
    "*let let let bn=অনুমতি দেওয়া",
    "lick",
    "*lie lay lain sense=recline",
    "*lie sense=tell an untruth",
    "lift",
    "*light lit lit",
    "like",
    "limp",
    "listen bn=শোনা",
    "*live bn=বাস করা",
    "*look bn=তাকানো",
    "*lose lost lost bn=হারানো",
    "love bn=ভালোবাসা",
  ],
};
