import { type IRawVerbGroup } from './schema';

/**
 * A to D — the first quarter of the thousand.
 *
 * Written the way `schema.ts` describes: a regular verb is **one word**,
 * because its other four forms are derived rather than stored. Three words
 * means the past and the participle are irregular; an `ing=` or `s=` token
 * means the spelling rule does not reach that form and the exception is
 * recorded rather than guessed at. A leading `*` marks one of the hundred a
 * learner meets first.
 */
export const VERBS_A_D: IRawVerbGroup = {
  range: 'a-d',
  entries: [
    "abash",
    "abate",
    "abide abode abode",
    "absorb",
    "accept",
    "accompany",
    "ache",
    "achieve",
    "acquire",
    "act",
    "add",
    "address",
    "adjust",
    "admire",
    "admit admitted admitted ing=admitting",
    "advise",
    "afford",
    "agree",
    "alight alit alit",
    "allow",
    "animate",
    "announce",
    "answer bn=উত্তর দেওয়া",
    "apologize",
    "appear",
    "applaud",
    "apply",
    "approach",
    "approve",
    "argue",
    "arise arose arisen",
    "arrange",
    "arrest",
    "*ask bn=জিজ্ঞাসা করা",
    "assert",
    "assort",
    "astonish",
    "attack",
    "attend",
    "attract",
    "audit",
    "avoid",
    "awake awoke awoken",
    "bang",
    "banish",
    "bash",
    "bat",
    "*be was/were been ing=being s=is bn=হওয়া",
    "bear bore born sense=be born",
    "bear bore borne sense=carry, endure",
    "beat beat beaten",
    "beautify",
    "*become became become bn=হয়ে ওঠা",
    "befall befell befallen",
    "beg",
    "*begin began begun ing=beginning bn=শুরু করা",
    "behave",
    "behold beheld beheld",
    "believe bn=বিশ্বাস করা",
    "belong",
    "bend bent bent",
    "bereave bereft bereft",
    "beseech besought besought",
    "bet bet bet",
    "betray",
    "bid bade bidden sense=command, or say a farewell",
    "bid bid bid sense=offer a price",
    "bind bound bound",
    "bite bit bitten",
    "bleed bled bled",
    "bless",
    "blossom",
    "blow blew blown",
    "blur",
    "blush",
    "board",
    "boast",
    "boil",
    "bow",
    "box",
    "bray",
    "*break broke broken bn=ভাঙা",
    "breathe",
    "breed bred bred",
    "*bring brought brought bn=আনা",
    "broadcast broadcast broadcast",
    "brush",
    "*build built built bn=নির্মাণ করা",
    "burn burnt burnt",
    "burst burst burst",
    "bury",
    "bust bust bust",
    "*buy bought bought bn=কেনা",
    "buzz",
    "calculate",
    "*call bn=ডাকা",
    "canvass",
    "capture",
    "caress",
    "carry bn=বহন করা",
    "carve",
    "cash",
    "cast cast cast",
    "catch caught caught bn=ধরা",
    "cause",
    "cease",
    "celebrate",
    "challenge",
    "change bn=পরিবর্তন করা",
    "charge",
    "chase",
    "chat",
    "check",
    "cheer",
    "chew",
    "chide chid chid/chidden",
    "chip",
    "choke",
    "*choose chose chosen bn=বেছে নেওয়া",
    "classify",
    "clean",
    "cleave clove/cleft cloven/cleft",
    "click",
    "climb",
    "cling clung clung",
    "close bn=বন্ধ করা",
    "clothe clad clad",
    "clutch",
    "co-operate",
    "collapse",
    "collect",
    "colour",
    "*come came come bn=আসা",
    "comment",
    "compare",
    "compel compelled compelled ing=compelling",
    "compete",
    "complain",
    "complete",
    "conclude",
    "conduct",
    "confess",
    "confine",
    "confiscate",
    "confuse",
    "congratulate",
    "connect",
    "connote",
    "conquer",
    "consecrate",
    "consent",
    "conserve",
    "consider",
    "consign",
    "consist",
    "console",
    "consort",
    "conspire",
    "constitute",
    "constrain",
    "construct",
    "construe",
    "consult",
    "contain",
    "contemn",
    "contend",
    "contest",
    "continue",
    "contract",
    "contradict",
    "contrast",
    "contribute",
    "contrive",
    "control controlled controlled ing=controlling",
    "convene",
    "converge",
    "converse",
    "convert",
    "convey",
    "convict",
    "convince",
    "coo",
    "cook bn=রান্না করা",
    "cool",
    "cope coped cope",
    "copy",
    "correct",
    "correspond",
    "corrode",
    "corrupt",
    "cost cost cost",
    "cough",
    "counsel counselled counselled ing=counselling",
    "count bn=গণনা করা",
    "course",
    "cover",
    "cower",
    "crack",
    "crackle",
    "crash",
    "crave",
    "create",
    "creep crept crept",
    "crib",
    "cross",
    "crowd",
    "crush",
    "cry bn=কাঁদা",
    "curb",
    "cure",
    "curve",
    "*cut cut cut bn=কাটা",
    "cycle",
    "damage",
    "damp",
    "dance bn=নাচা",
    "dare",
    "dash",
    "dazzle",
    "deal dealt dealt",
    "decay",
    "decide",
    "declare",
    "decorate",
    "decrease",
    "dedicate",
    "delay",
    "delete",
    "deny",
    "depend",
    "deprive",
    "derive",
    "describe",
    "desire",
    "destroy",
    "detach",
    "detect",
    "determine",
    "develop",
    "*die bn=মারা যাওয়া",
    "differ",
    "dig dug dug",
    "digest",
    "dim",
    "diminish",
    "dine",
    "dip",
    "direct",
    "disappear",
    "discover",
    "discuss",
    "disobey",
    "display",
    "dispose",
    "distribute",
    "disturb",
    "disuse",
    "dive",
    "divide",
    "*do did done bn=করা",
    "donate",
    "download",
    "drag",
    "draw drew drawn bn=আঁকা",
    "dream dreamt dreamt",
    "dress",
    "drill",
    "*drink drank drunk bn=পান করা",
    "*drive drove driven bn=চালানো",
    "drop",
    "dry",
    "dump",
    "dwell dwelt dwelt",
    "dye",
  ],
};
