import { type IRawVerbGroup } from './schema';

/**
 * S to Z — and the irregular tail, where most of the trouble is.
 *
 * Written the way `schema.ts` describes: a regular verb is **one word**,
 * because its other four forms are derived rather than stored. Three words
 * means the past and the participle are irregular; an `ing=` or `s=` token
 * means the spelling rule does not reach that form and the exception is
 * recorded rather than guessed at. A leading `*` marks one of the hundred a
 * learner meets first.
 */
export const VERBS_S_Z: IRawVerbGroup = {
  range: 's-z',
  entries: [
    "sabotage",
    "sack",
    "sacrifice",
    "sadden",
    "saddle",
    "sag",
    "sail",
    "sally",
    "salute",
    "salvage",
    "salve",
    "sample",
    "sanctify",
    "sanction",
    "sap",
    "saponify",
    "sash",
    "sashay",
    "sass",
    "sate",
    "satiate",
    "satirise",
    "satisfy",
    "saturate",
    "saunter",
    "save",
    "savor",
    "savvy",
    "saw sawed sawn",
    "*say said said bn=বলা",
    "scab",
    "scabble",
    "scald",
    "scale",
    "scam",
    "scan",
    "scant",
    "scar",
    "scare",
    "scarify",
    "scarp",
    "scat",
    "scatter",
    "scold",
    "scorch",
    "scowl",
    "scrawl",
    "scream",
    "screw",
    "scrub",
    "search",
    "seat",
    "secure",
    "*see saw seen bn=দেখা",
    "seek sought sought",
    "*seem bn=মনে হওয়া",
    "seize",
    "select",
    "*sell sold sold bn=বিক্রি করা",
    "*send sent sent bn=পাঠানো",
    "sentence",
    "separate",
    "set set set",
    "sever",
    "sew sewed sewn",
    "*shake shook shaken bn=ঝাঁকানো",
    "shape",
    "share",
    "shatter",
    "shave shove shaven",
    "shear shore shorn",
    "shed shed shed",
    "*shine shone shone",
    "shirk",
    "shit shit shit",
    "shiver",
    "shock",
    "shoe shod shod",
    "*shoot shot shot bn=গুলি করা",
    "shorten",
    "shout",
    "*show showed shown bn=দেখানো",
    "shrink shrank shrunk",
    "shun",
    "shut shut shut",
    "sight",
    "signal signalled signalled ing=signalling",
    "signify",
    "*sing sang sung bn=গান গাওয়া",
    "*sink sank sunk",
    "sip",
    "*sit sat sat bn=বসা",
    "ski",
    "skid",
    "slam",
    "slay slew slain",
    "*sleep slept slept bn=ঘুমানো",
    "slide slid slid/slide",
    "slim",
    "sling slung slung",
    "slink slunk slunk",
    "slip",
    "slit slit slit",
    "smash",
    "smell smelt smelt",
    "smile",
    "smite smote smitten",
    "smooth s=smoothes",
    "smother",
    "snap",
    "snatch",
    "sneak",
    "sneeze",
    "sniff",
    "soar",
    "sob",
    "solicit",
    "solve",
    "soothe",
    "sort",
    "sow",
    "sparkle",
    "*speak spoke spoken bn=কথা বলা",
    "speed sped sped",
    "spell spelt spelt",
    "*spend spent spent bn=ব্যয় করা",
    "spill spilt spilt",
    "spin span/spun spun",
    "spit spat/spit spat/spit",
    "split split split",
    "spoil spoilt spoilt",
    "spray",
    "*spread spread spread",
    "spring sprang sprung",
    "sprout",
    "squeeze",
    "*stand stood stood bn=দাঁড়ানো",
    "stare",
    "*start bn=শুরু করা",
    "state",
    "*stay bn=থাকা",
    "*steal stole stolen",
    "steep",
    "stem",
    "step",
    "sterilize",
    "*stick stuck stuck",
    "stimulate",
    "sting stung stung",
    "stink stank stunk",
    "stir",
    "stitch",
    "stoop",
    "stop bn=থামা",
    "store",
    "strain",
    "stray",
    "stress",
    "stretch",
    "strew strewed strewn",
    "stride strode stridden",
    "strike struck struck/stricken",
    "string strung strung",
    "strive strove striven",
    "study bn=পড়াশোনা করা",
    "submit submitted submitted ing=submitting",
    "subscribe",
    "subtract",
    "succeed",
    "suck",
    "suffer",
    "*suggest",
    "summon",
    "supply",
    "support",
    "suppose",
    "surge",
    "surmise",
    "surpass",
    "surround",
    "survey",
    "survive",
    "swallow",
    "sway",
    "swear swore sworn",
    "sweat sweat sweat",
    "sweep swept swept",
    "swell swelled swollen",
    "*swim swam swum bn=সাঁতার কাটা",
    "swing swung swung",
    "swot",
    "*take took taken bn=নেওয়া",
    "*talk bn=কথা বলা",
    "tap",
    "taste",
    "tax",
    "*teach taught taught bn=শেখানো",
    "tear tore torn",
    "tee",
    "*tell told told bn=বলা",
    "tempt",
    "tend",
    "terminate",
    "terrify",
    "test",
    "thank",
    "*think thought thought bn=ভাবা",
    "thrive throve thriven",
    "*throw threw thrown bn=ছোড়া",
    "thrust thrust thrust",
    "thump",
    "tie",
    "tire",
    "toss",
    "touch",
    "train",
    "trample",
    "transfer transferred transferred ing=transferring",
    "transform",
    "translate",
    "trap",
    "travel travelled travelled ing=travelling bn=ভ্রমণ করা",
    "tread trod trodden",
    "treasure",
    "treat",
    "tree",
    "tremble",
    "triumph",
    "trust",
    "*try bn=চেষ্টা করা",
    "*turn bn=ঘোরানো",
    "type",
    "typeset typeset typeset ing=typesetting",
    "*understand understood understood bn=বোঝা",
    "undo undid undone",
    "uproot",
    "upset upset upset ing=upsetting",
    "urge",
    "*use bn=ব্যবহার করা",
    "utter",
    "value",
    "vanish",
    "vary",
    "verify",
    "vex",
    "vie",
    "view",
    "violate",
    "vomit",
    "*wake woke woken bn=জেগে ওঠা",
    "*walk bn=হাঁটা",
    "wander",
    "*want bn=চাওয়া",
    "warn",
    "waste",
    "*watch bn=দেখা",
    "water",
    "wave",
    "wax",
    "waylay waylaid waylaid",
    "*wear wore worn bn=পরা",
    "weave wove woven",
    "wed wed wed",
    "weep wept wept",
    "weigh",
    "welcome",
    "wend went went",
    "wet wet wet",
    "whip",
    "whisper",
    "*win won won bn=জেতা",
    "wind wound wound",
    "wish",
    "withdraw withdrew withdrawn",
    "*work bn=কাজ করা",
    "worry",
    "worship worshipped worshipped ing=worshipping",
    "wring wrung wrung",
    "*write wrote written bn=লেখা",
    "yawn",
    "yell",
    "yield",
    "zinc zincked zincked ing=zincking",
    "zoom",
  ],
};
