import { type IRawVerbGroup } from './schema';

/**
 * M to R.
 *
 * Written the way `schema.ts` describes: a regular verb is **one word**,
 * because its other four forms are derived rather than stored. Three words
 * means the past and the participle are irregular; an `ing=` or `s=` token
 * means the spelling rule does not reach that form and the exception is
 * recorded rather than guessed at. A leading `*` marks one of the hundred a
 * learner meets first.
 */
export const VERBS_M_R: IRawVerbGroup = {
  range: 'm-r',
  entries: [
    "magnify",
    "maintain",
    "*make made made bn=তৈরি করা",
    "manage",
    "march",
    "mark",
    "marry",
    "mash",
    "match",
    "matter",
    "*mean meant meant bn=বোঝানো",
    "measure",
    "*meet met met bn=দেখা করা",
    "melt",
    "merge",
    "mew",
    "migrate",
    "milk",
    "mind",
    "mislead misled misled",
    "miss",
    "mistake mistook mistaken",
    "misuse",
    "mix",
    "moan",
    "modify",
    "moo",
    "motivate",
    "mould",
    "moult",
    "*move bn=সরানো",
    "mow mowed mown",
    "multiply",
    "murmur",
    "nail",
    "nap",
    "*need bn=প্রয়োজন হওয়া",
    "neglect",
    "nip",
    "nod",
    "note",
    "notice",
    "notify",
    "nourish",
    "nurse",
    "obey",
    "oblige",
    "observe",
    "obstruct",
    "obtain",
    "occupy",
    "occur occurred occurred ing=occurring",
    "offer",
    "offset offset offset ing=offsetting",
    "omit omitted omitted ing=omitting",
    "ooze",
    "*open bn=খোলা",
    "operate",
    "opine",
    "oppress",
    "opt",
    "optimize",
    "order",
    "organize",
    "originate",
    "output output output ing=outputting",
    "overflow",
    "overtake overtook overtaken",
    "owe",
    "own",
    "pacify",
    "paint",
    "pardon",
    "part",
    "partake partook partaken",
    "participate",
    "*pass bn=পাশ করা",
    "paste",
    "pat",
    "patch",
    "pause",
    "*pay paid paid bn=পরিশোধ করা",
    "peep",
    "perish",
    "permit permitted permitted ing=permitting",
    "persuade",
    "phone",
    "place",
    "plan",
    "*play bn=খেলা",
    "plead pled pled",
    "please",
    "plod",
    "plot",
    "pluck",
    "ply",
    "point",
    "polish",
    "pollute",
    "ponder",
    "pour",
    "pout",
    "practise",
    "praise",
    "pray",
    "preach",
    "prefer preferred preferred ing=preferring",
    "prepare",
    "prescribe",
    "present",
    "preserve",
    "preset preset preset ing=presetting",
    "preside",
    "press",
    "pretend",
    "prevent",
    "print",
    "proceed",
    "produce",
    "progress",
    "prohibit",
    "promise",
    "propose",
    "prosecute",
    "protect",
    "prove",
    "provide",
    "pull",
    "punish",
    "purify",
    "push",
    "*put put put bn=রাখা",
    "qualify",
    "quarrel quarrelled quarrelled ing=quarrelling",
    "question",
    "quit quit quit ing=quitting",
    "race",
    "rain",
    "rattle",
    "reach",
    "*read read read bn=পড়া",
    "realize",
    "rebuild rebuilt rebuilt",
    "recall",
    "recast recast recast",
    "receive",
    "recite",
    "recognize",
    "recollect",
    "recur recurred recurred ing=recurring",
    "redo redid redone",
    "reduce",
    "refer referred referred ing=referring",
    "reflect",
    "refuse",
    "regard",
    "regret regretted regretted ing=regretting",
    "relate",
    "relax",
    "rely",
    "remain",
    "remake remade remade",
    "remove",
    "rend rent rent",
    "renew",
    "renounce",
    "repair",
    "repeat",
    "replace",
    "reply",
    "report",
    "request",
    "resell resold resold",
    "resemble",
    "reset reset reset ing=resetting",
    "resist",
    "resolve",
    "respect",
    "rest",
    "restrain",
    "retain",
    "retch",
    "retire",
    "*return bn=ফিরে আসা",
    "reuse",
    "review",
    "rewind rewound rewound",
    "rid rid rid",
    "*ride rode ridden bn=চড়া",
    "*ring rang rung bn=বাজানো",
    "*rise rose risen bn=ওঠা",
    "roar",
    "rob",
    "roll",
    "rot",
    "rub",
    "rule",
    "*run ran run bn=দৌড়ানো",
    "rush",
  ],
};
